export default {
  notifications : "Notifications",
  mapView : "Map View",
  editDetail : "Edit Details",
  complaint : "Complaints",
  logout : "Log out",
  welcome : "Welcome",
  name : "Name",
  phoneNumber : "Phone Number",
  email : "Email",
  address : "Address",
  select_your_ward : "Please Select Your Are",
  update_current_location: "Update Current Location",
  submit: "Submit",
  details : "Details",
  loading : "Loading ...",
  loading_com : "Loading Complaints",
  loading_book : "Loading Bookings",
  take_picture : "Take Picture",
  edit_picture : "Edit Picture",
  type_of_complaint : "Type Of Complaint",
  message : "Message",
  send : "Send",
  send_otp : "Send OTP",
  confirm : "Confirm",
  complaint_message : "Complaint Message",
  confirmation_code : "Confirmation Code",
  firstName_lastName : "FirstName LastName",
  search : "Search",
  select_language : "Change Language",
  we_shall_contact_you_soon: "Your Complaint Has Registered Sucessfully",
  we_shall_contact_you_soon_T: "Your Booking Has Registered Sucessfully",
  please_enter_complaint_message: "Please Enter Complaint Message",
  alert_c : 'ALERT',
  ok_c : "OK",
  cancel : "Cancel",
  save : "save",
  please_grant_location_permission : "Please Grant Location Permission",
  please_enter_10_digit_phonenumber : "Please Enter Your 10 Digit Phone Number",
  please_enter_valid_phoneNumber : "Please Enter Your Valid 10 Digit Phone Number",
  please_enter: "Please Enter",
  message_sent_successfully: "Message Sent Successfully",
  your_notifications: "Your Notifications",
  register_your_complaint: "Register Your Complaint",
  image_loading : "Image Loading",
  please_wait_until_image_is_loaded: "Please Wait Until Photo Is Loaded",
  oops_there_is_an_error_while_getting_image_url: "Oops!! There Is An Error While Getting Image Url",
  oops_there_is_an_error_whie_storing_image: "Oops!! There Is An Error While Storing Image",
  your_complaints_list : "Your Complaints List",
  add_complaint : "Add Complaint",
  your_complaints : "Your Complaints",
  about_us : "About Us",
  landmark : "Landmark",
  near_shiv_temple: "Near shiva temple",
  close_c : "Close",
  delete_c : "Delete",
  otp_sent : "OTP Has Sent",
  an_initiative_by : "An Initiative By",
  deleting_notif : "Deleting Notification",
  fetching_notification : "Fetching Notification",
  notif_welcome_msg : "Don't Throw Garbage All Around. Use Dustbin. Our City Is Our Own House. Clean City, Clean House.",
  enter_mobile_number : "Enter Your Phone Number",
  we_have_sent_otp_on : "We Have Sent OTP",
  reeenter_number : "Re Enter Number",
  resend_otp : "Resend OTP",
  see_nearby_garbage_vehicles : "See Nearby Garbage Vehicle",
  we_will_access_your_location : "We Will Access Your Location",
  allow_c : "ALLOW",
  ward: "Ward",
  comissioner : "Municipal Commissioner",
  mayor : "Chairperson",
  otp : "OTP",
  collector : "District Collector",
  adm : "Additional District Magistrate",
  executive_officer : "Executive Officer",
  please_confirm : "Please Confirm",
  for_any_query_call_on_this_number : "For Any Query Call On This Number",
  call : "Call",
  sub_collector: "Sub Collector",
  no_active_complaints: "No Active Complaint !!!",
  no_complaints_message: "There Are No Active Complaints Filed By You. Start Filing Complaint Of Your Area.",
  places: "Places",
  register_your_complaint: "Register Your Complaint",
  mapViewFilters: "Map View Filters",
  vehicles: "Vehicles",
  places: "Places",
  park: "Park",
  hospital: "Hospital",
  dumping_point: "Dumping Point",
  toilet: "Toilet",
  signup_to_continue: "Sign Up To Continue!!!",
  editYourDetail : "Edit Your Details",
  places_around_you : "Places Around You",
  no_places_yet: "No Place Found.",
  no_places_message: "No Place Has Been Found In Your Area",
  placesFilter: "Places Filter",
  filter_c: "Filter",
  save_c: "Save",
  please_enter_complaint_typesOfcomplaint : "Please Select Type Of Complaint",
  view_more: "View More",
  complaint_id: "Complaint Id",
  image: "Image",
  message : "Message",
  // types of garbage
  garbage_dump : "Garbage Dump",
  garbage_vehicle_Not_arrived : "Garbage Vehicle Not Arrived",
  dustbins_not_cleaned: "Dustbins Not Cleaned",
  sweeping_not_done: "Sweeping Not Done",
  dead_animal: "Dead Animal",
  public_toilets_cleaning: "Public Toilets Cleaning",
  public_toilets_blockage: "Public Toilets Blockage",
  no_water_supply_in_public_toilets: "No Water Supply In Public Toilets",
  no_electricity_in_public_toilets: "No Electricity In Public Toilets",
  others: "Others",
  drain_not_cleaned : "Drain Not Cleaned",
  please_grant_location_permission_c : "PLEASE GRANT LOCATION PERMISSION",
  error_in_getting_current_location: "Error In Getting Current Location",
  error_in_getting_location_please_set_location_in_map : "Please Provide Your Current Location.",
  or_c : "OR",
  select_location : "Select Location",
  select_location_from_map : "Select Location From Map",
  select_current_location : "Select Current Location",
  add_task: "Add Task",
  requestVehicle: "Reuest Vehicle",
  request_vehicle: "Request Vehicle",
  your_requests: "Your Request",
  no_active_requests: "There Are No Active Request",
  no_requests_message: "There Are No Active Request From You. You Can Request A Garbage Vehicle At Your Place",
  please_enter_request_vehicle_message: "Please Enter The Message",
  please_enter_typesOfRequestVehicle: "Please Select Type Of Request Vehicle",
  request_your_vehicle: "Request Your Vehicle",
  type_of_request_vehicle: "Type Of Request Vehicle",
  request: "Request",
  request_vehicle_note: "Note: The Vehicles Requested Will Be Subjected To Charge",
  delete: "Delete",
  domestic_waste: "Domestic\nWaste",
  water_tank: "Water\nTank",
  cesspool_tank: "Cesspool\nWaste",
  party_waste: "Party\nWaste",
  commercial_waste: "Commercial\nWaste",
  construction_waste: "Construction\nWaste",
  description: "Description",
  enter_your_suggestion: "Enter Your Suggestion",
  suggestion: "Suggestion",
  mark_it_home_address : "Mark It As Home Address",
  segregated_waste_throw:"1.Do You Give Segregated Waste(Wet&Dry) To Your Waste Collected?",
  searching_nearest_publicToilet:"2.Do You Know How Can You Search Nearest Public Toilet On Google?",
  neighbourhood_area:"3.Do You Find Your Neighbourhood Area Always Clean?",
  home_composting:"4.Do You Know About Home Composting?",
  your_age:"5.What Is Your Age?",
  municipal_corporation : "Municipal Corporation",
  municipal_council : "Municipal Council",
  history : "History",
  
  contactUs : "ContactUs",
  notice_board : "Notice Board",
  track_garbageVan : "Track GarbageVan",
  garbageVan : "Garbage Van",
  toilet_Locator   : "Toilet Locator",
  toilets : "Toilets",
  community : "Community",
  payments : "Payments",
  update_account : "you Have Sucessfully Updated Your Account.",
  create_account : "you Have Sucessfully Created An Account.",
  share: "Share",
  contact_us : "Contact Us",
  create_new_complaint : "Create New Complaint",
  create_new_booking : "Create New Booking",
  add_photo_or_video : "Add Photo Or Video",
  click_to_attach : "Click To Attach Photo",
  booking_type : "Type Of Booking",
  booking_date : "Booking Date",
  quantity : "Quantity",
  price : "Price",
  proceed : "Proceed",
  please_select_bookingDate : "Please Select Booking Date",
  booking_confirmation : "Booking Confirmation", 
  pay_now : "Pay Now",
  cash_on_delivery : "Cash On Delivery",
  _tags:"Tags",
  prefered_lan :"Preffered Languages",
  _profile :"Profile",
  no_history_found_for_this_date : "No History Found For This Date",
  bookings_not_available : "bookings Were Not Available For You.Please Contact Your Admin For Further Details..",
  mobile_num_change : "Re-Enter Number",
  update :"Update",
  signup : "Sign Up",
  skip : "Skip",
  proceed : "Proceed",
  houseno : "House No",
  wardnum : "Ward Number",
  tagurself : "Tag Youself",
  locateme : "Locate Me",
  settings : "Settings",
  location :"Location",
  add_location :"Add Location",
  update_location : "Update Location",
  edit_location : "Edit Location",
  alert :"Alerts",
  show_alert:"Show Alert",
  show_notification :"Show Notification",
  assigned_tags : "Assigned Tags",

  add_tag :"Add Tag",
  add_newtag : "Add New Tag",
  ward_details : "Ward Details",
  show_alerts : "Show Alerts",
  make_my_profile_private : "Make My Profile Private",
  new_booking :"New Booking",
  new_complaint : "New Complaint",
  complaint_date : "Complaint Date",
  complaint_no  :"Complaint No",
  muncipality : "Muncipality",
  list_of_vehicles_available:"List Of Vehicles Available On",
  enter_otp : "Enter OTP",

  no_notification:"No Notifications",
  retake:"Retake",
  post_complaint:"Create New Complaint",
  select_complaint:"Select Complaint Type",
  current_location:"Current Location",
  describe_issue:"Describe Issue",
  capture_image:"Capture Image",
  select_type:"Select Type",
  booking : "Bookings",
  active:"Active",
  assign:"Assigned",
  close:"Closed",
  _close:"Close",
  refresh:"Refresh",
  age:"Age",
  other_num:"Other Numbers",
  feedback:"Feedback",
  ward_d:"Ward Details",
  photos:'Photos',
  navigation:"Navigation",
  view_n:"View Navigation",
  otp_sent_to : "The OTP Has Been Sent To Your Registered Phone Number",
  dear_user : "Dear User",
  congrats : "Congrats!",
  Call_JMC : "Call JMC Helpline",
  // your_house_holding : ""
  full_name : "Full Name",
  mobile_num : "Mobile Number",
  emailid : "Email Id",
  requestType : "RequestType",
  bookedOn : "Booked On",
  bookedFor : "Delivered On",
  assignedTo: "AssignedTo",
  tId : "TaskId",
  req_veh : "Requested Vehicle",
  taskType : "Task Type",
  ACTIVE : "ACTIVE",
  ASSIGNED : "ASSIGNED",
  CLOSED : "CLOSED",
  PENDING : "PENDING",
  userprofile : "User Profile",
  editprofile : "Edit Profile",
  area : "Area",
  attended_by : "Attended By",
  time : "Time",
  acknowledgement : "Acknowledgement",
  segregation : "Segregation",
  no_data_found : "No Data Found For This Date",
  go_to_c : "Show Calendar",
  hold_on : "Hold on!",
  tag_added : "New Tag Added Sucessfully!",
  garbage_collected : "Garbage Collected",
  garbage_segregation : "Garbage Seggregation Not Done",
  garbage_picker_absent : "Garbage Picker Absent",
  unavailable:"unAvailable",
  saving_complaint : "Saving Complaint",
  command_center : "Command Center",
  please_enter_valid_otp : "Please Enter Valid OTP",
  keep_our_mun : "Keep Our Buguda Clean",
  please_enter_suggerstion : "Please Enter Your Suggestion",
  please_enter_age : "Please Enter Age",
  your_feedback_submitted : "Your Feedback Sucessfully Submitted",
  keep_our : "Keep Our", 
  clean : "Clean",
  //Newly Added
  app_version : "App Version :",
  exit_app : "Exit App",
  enter_your_text : "Enter Your Text",
  choose_image : "Choose Image",
  click_image : "Click Image",
  dear_user : "Dear User",
  location_updated : "Your Location Sucessfully Updated",
  pick_image : "Upload Image",
  home_message : "Keep our Dehri clean",
  upload_image : "Please Upload Image",
  please_enter_number : "Please Enter Your Phone Number",
  please_enter_valid_info : "Please Enter OTP",
  please_select_image : "Please Select Image",
  while_storing_image : "Oops!! There Is An Error While Storing Image",
  map : "Map",
  satelite : "Satelite",
  failed_to_insert_user: "Failed To Insert User",
  please_select_c_type : "Select Complaint Type",
  please_enter_comment : "Please Enter Comment",
  comment : "Comment",
  please_select_b_type : "Select Booking Type",
  please_select_waste_type: "Please Select Booking Type",
  req_veh : "Booking Type",
  select_task:"Select Booking",
  confirm_to_exit : "Do You Want To Exit App?",
  history_t : "History of",
  please_select_all : "Please Answer All Questions",
  please_select_location_by_clicking : "Click On Red Colour 'Location' Button And Save Your Current Location",
  please_select_location_by_clicking_mapview : "click On Red Colour 'Location' Button And View Your Current Location",
  please_enter_d_no : "Please Enter Your Door Number",
  user_with_same_d_no_exists : "User With Same Door Number Exist",
  d_no : "Door No",
  cannot_update : "You Are Not Allowed To Update This Household . Please Contact Admin",
  please_enter_d_no_properly : "Door Number Should Be In Alphanumeric Capital Letter. \n(Hint: * A Capital (Uppercase) Letter\n* A Number \n* Minimum 1 Character)",
  getting_this_month_report : "Please Wait Getting Current Month Report",
  please_switch_location : "Please Switch On Your Location In Phone",
  switch_on_location : "Switch On Your Location",
  location_permission : 'You Have Not Given Location Permission For App. So Kindly Give Location Permission From The App',
  camera_permission : "You Have Not Given Camera Permission For App. So Kindly Give Camera Permission From The App",
  please_assign_tag_to_you : "Choose Your Tags From The Below List",
  permission_to_acess_storage : "You Have Not Given Storage Permission For The App. So Kindly Give The Storage Permission From The App",
  all : "All",
  please_enter_name_properly : "Please Do Not Leave 'Name' With Empty Spaces.",
  please_enter_name : "Please Enter Your Name",
  please_enter_address : "Please Choose Map To Get Your Current Location or Please Provide Your address in this 'Street, Area and Pincode' Format",
  please_enter_fatherName : "Please Enter Your Father Name",
  please_enter_fatherName_properly : "Please Do Not Leave 'Father Name' With Empty Spaces.",
  father_name : "Father Name",
  yes : "Yes",
  no : "No",
  garbage_picker_present : "Garbage Picker Present",
  stAndArea : "Street, Area and Pincode",
  getting_loc : "Getting Location",
  unable_to_fetch_exact_location : "Unable To Fetch Exact Location. Please Click On Red Colour 'Location' Button",
  close_cm : "CLOSE",
  failed_to_get_location : "Failed To Get Location",
  fetching_location : "Fetching Location",
  createAccount : "Create Account",
  location_captured : "Location Captured Sucessfully",
  calendar : "Calendar",
  please_select_complaint_location : "Please Select Complaint Location"
  









}