export default {
  notifications : "Notifications",
  mapView : "Map View",
  editDetail : "Edit Details",
  complaint : "Complaints",
  logout : "Log out",
  welcome : "Welcome",
  name : "Name",
  phoneNumber : "Phone Number",
  email : "Email",
  address : "Address",
  select_your_ward : "Select your ward",
  update_current_location: "Update current location",
  submit: "Submit",
  details : "Details",
  loading : "Loading ...",
  loading_com : "Loading Complaints",
  loading_book : "Loading Bookings",
  take_picture : "Take Picture",
  edit_picture : "Edit Picture",
  type_of_complaint : "Type of complaint",
  message : "Message",
  send : "Send",
  send_otp : "Send OTP",
  confirm : "Confirm",
  complaint_message : "Complaint Message",
  confirmation_code : "Confirmation Code",
  firstName_lastName : "FirstName LastName",
  search : "Search",
  select_language : "Change Language",
  we_shall_contact_you_soon: "Your Complaint is Registered Sucessfully",
  we_shall_contact_you_soon_T: "Your Task is Registered Sucessfully",
  please_enter_complaint_message: "Please enter complaint message",
  alert_c : 'ALERT',
  ok_c : "OK",
  cancel : "Cancel",
  save : "save",
  please_grant_location_permission : "Please grant location permission",
  please_enter_10_digit_phonenumber : "Please enter valid 10 digit phoneNumber",
  please_enter_valid_phoneNumber : "Please enter valid phonenumber",
  please_enter: "Please enter",
  message_sent_successfully: "Message sent successfully",
  your_notifications: "Your Notifications",
  register_your_complaint: "Register Your Complaint",
  image_loading : "Image Loading",
  please_wait_until_image_is_loaded: "Please wait until photo is loaded",
  oops_there_is_an_error_while_getting_image_url: "Oops!! there is an error while getting image url",
  oops_there_is_an_error_whie_storing_image: "Oops!! there is an error while storing image",
  your_complaints_list : "Your complaints list",
  add_complaint : "Add Complaint",
  your_complaints : "Your Complaints",
  about_us : "About Us",
  landmark : "landmark",
  near_shiv_temple: "Near shiva temple",
  close_c : "Close",
  delete_c : "Delete",
  otp_sent : "OTP Sent",
  an_initiative_by : "An initiative by",
  deleting_notif : "Deleting Notification",
  fetching_notification : "Fetching Notification",
  notif_welcome_msg : "Don't throw garbage all around. Use dustbin. Our city is our own house. Clean city, Clean house.",
  enter_mobile_number : "Enter Your Mobile Number",
  we_have_sent_otp_on : "We have sent OTP",
  reeenter_number : "Re enter number",
  resend_otp : "Resend OTP",
  see_nearby_garbage_vehicles : "See nearby garbage vehicle",
  we_will_access_your_location : "We will access your location",
  allow_c : "ALLOW",
  ward: "Ward",
  comissioner : "Municipal Commissioner",
  mayor : "Chairperson",
  otp : "OTP",
  collector : "District Collector",
  adm : "Additional District Magistrate",
  executive_officer : "Executive Officer",
  please_confirm : "Please Confirm",
  for_any_query_call_on_this_number : "For any query call on this number",
  call : "Call",
  sub_collector: "Sub Collector",
  no_active_complaints: "No Active Complaint !!!",
  no_complaints_message: "There are no active complaints filed by you. Start filing complaint of your area.",
  places: "Places",
  register_your_complaint: "Register your complaint",
  mapViewFilters: "Map View Filters",
  vehicles: "Vehicles",
  places: "Places",
  park: "Park",
  hospital: "Hospital",
  dumping_point: "Dumping Point",
  toilet: "Toilet",
  signup_to_continue: "Sign up to continue!!!",
  editYourDetail : "Edit Your Details",
  places_around_you : "Places around you",
  no_places_yet: "No Place found.",
  no_places_message: "No place has been found in your area",
  placesFilter: "Places Filter",
  filter_c: "Filter",
  save_c: "Save",
  please_enter_complaint_typesOfcomplaint : "Please select type of complaint",
  view_more: "View More",
  complaint_id: "Complaint Id",
  image: "Image",
  message : "Message",
  // types of garbage
  garbage_dump : "Garbage dump",
  garbage_vehicle_Not_arrived : "Garbage Vehicle not arrived",
  dustbins_not_cleaned: "Dustbins not cleaned",
  sweeping_not_done: "Sweeping not done",
  dead_animal: "Dead animal",
  public_toilets_cleaning: "Public toilets cleaning",
  public_toilets_blockage: "Public toilets blockage",
  no_water_supply_in_public_toilets: "No water supply in public toilets",
  no_electricity_in_public_toilets: "No electricity in public toilets",
  others: "Others",
  drain_not_cleaned : "Drain not cleaned",
  please_grant_location_permission_c : "PLEASE GRANT LOCATION PERMISSION",
  error_in_getting_current_location: "Error in getting current location",
  error_in_getting_location_please_set_location_in_map : "Please provide your current location.",
  or_c : "OR",
  select_location : "Select Location",
  select_location_from_map : "Select Location from map",
  select_current_location : "Select current location",
  add_task: "Add Task",
  requestVehicle: "Reuest vehicle",
  request_vehicle: "Request Vehicle",
  your_requests: "Your request",
  no_active_requests: "There are no active request",
  no_requests_message: "There are no active request from you. You can request a garbage vehicle at your place",
  please_enter_request_vehicle_message: "Please enter the message",
  please_enter_typesOfRequestVehicle: "Please select type of request vehicle",
  request_your_vehicle: "Request your vehicle",
  type_of_request_vehicle: "Type of request vehicle",
  request: "Request",
  request_vehicle_note: "Note: The vehicles requested will be subjected to charge",
  delete: "Delete",
  domestic_waste: "Domestic\nWaste",
  water_tank: "Water\nTank",
  cesspool_tank: "Cesspool\nWaste",
  party_waste: "Party\nWaste",
  commercial_waste: "Commercial\nWaste",
  construction_waste: "Construction\nWaste",
  description: "Description",
  enter_your_suggestion: "Enter Your Suggestion",
  suggestion: "Suggestion",
  mark_it_home_address : "Mark it as home address",
  segregated_waste_throw:"1.Do you give segregated waste(Wet&Dry) to your waste collected?",
  searching_nearest_publicToilet:"2.Do you know how can you search nearest Public Toilet on Google?",
  neighbourhood_area:"3.Do you find your neighbourhood area always clean?",
  home_composting:"4.Do you know about home composting?",
  your_age:"5.What is your age?",
  municipal_corporation : "Municipal Corporation",
  municipal_council : "Municipal Council",
  history : "History",
  
  contactUs : "ContactUs",
  notice_board : "Notice Board",
  track_garbageVan : "Track GarbageVan",
  garbageVan : "Garbage Van",
  toilet_Locator   : "Toilet Locator",
  toilets : "Toilets",
  community : "Community",
  payments : "Payments",
  update_account : "you have sucessfully updated your account.",
  create_account : "you have sucessfully created an account.",
  share: "Share",
  contact_us : "Contact Us",
  create_new_complaint : "Create New Complaint",
  create_new_booking : "Create New Booking",
  add_photo_or_video : "Add photo or video",
  click_to_attach : "Click to attach photo",
  booking_type : "Type of Booking",
  booking_date : "Booking Date",
  quantity : "Quantity",
  price : "Price",
  proceed : "Proceed",
  please_select_bookingDate : "Please Select Booking Date",
  booking_confirmation : "Booking Confirmation", 
  pay_now : "Pay Now",
  cash_on_delivery : "Cash On Delivery",
  _tags:"Tags",
  prefered_lan :"Preffered Languages",
  _profile :"Profile",
  no_history_found_for_this_date : "No History Found For This Date",
  bookings_not_available : "bookings were not available for you.please contact your admin for further details..",
  mobile_num_change : "Change Mobile No",
  update :"Update",
  signup : "Sign Up",
  skip : "Skip",
  proceed : "Proceed",
  houseno : "House No",
  wardnum : "Ward Number",
  tagurself : "Tag youself",
  locateme : "Locate Me",
  settings : "Settings",
  location :"Location",
  add_location :"Add Location",
  update_location : "Update Location",
  alert :"Alerts",
  show_alert:"showAlert",
  show_notification :"showNotification",
  assigned_tags : "Assigned Tags",

  add_tag :"Add Tag",
  add_newtag : "Add NewTag",
  ward_details : "Ward Details",
  show_alerts : "Show Alerts",
  make_my_profile_private : "Make my profile private",
  new_booking :"New Booking",
  new_complaint : "New Complaint",
  complaint_date : "Complaint Date",
  complaint_no  :"Complaint No",
  muncipality : "Muncipality",
  list_of_vehicles_available:"List of vehicles available on",
  enter_otp : "Enter OTP",

  no_notification:"No Notifications",
  retake:"Retake",
  post_complaint:"Post Complaint",
  select_complaint:"Select Complaint Type",
  current_location:"Current location",
  describe_issue:"Describe issue",
  capture_image:"Capture Image",
  select_type:"Select type",
  booking : "Bookings",
  active:"Active",
  assign:"Assigned",
  close:"Closed",
  _close:"Close",
  refresh:"Refresh",
  age:"Age",
  other_num:"Other Numbers",
  feedback:"FeedBack",
  ward_d:"Ward Details",
  photos:'Photos',
  navigation:"Navigation",
  view_n:"View Navigation",
  otp_sent_to : "The OTP has been sent to your Mobile Number",
  dear_user : "Dear User",
  congrats : "Congrats!",
  Call_JMC : "Call JMC helpline",
  // your_house_holding : ""
  full_name : "Full Name",
  mobile_num : "Mobile Number",
  emailid : "Email Id",
  requestType : "RequestType",
  bookedOn : "Booked On",
  bookedFor : "Delivered On",
  assignedTo: "AssignedTo",
  tId : "TaskId",
  req_veh : "Requested Vehicle",
  taskType : "Task Type",
  ACTIVE : "ACTIVE",
  ASSIGNED : "ASSIGNED",
  CLOSED : "CLOSED",
  PENDING : "PENDING",
  userprofile : "User Profile",
  editprofile : "Edit Profile",
  area : "Area",
  attended_by : "Attended By",
  time : "Time",
  acknowledgement : "Acknowledgement",
  segregation : "Segregation",
  no_data_found : "No data found for this date",
  go_to_c : "Show Calendar",
  hold_on : "Hold on!",
  tag_added : "New Tag Added Sucessfully!",
  garbage_collected : "Garbage Collected",
  garbage_segregation : "Garbage seggregation not done",
  garbage_picker_absent : "Garbage picker absent",
  unavailable:"unavailable",
  saving_complaint : "Saving Complaint",
  command_center : "Command Center",
  please_enter_valid_otp : "Please Enter Valid OTP",
  keep_our_mun : "Keep Our Buguda Clean",
  please_enter_suggerstion : "Please Enter Suggetion",
  please_enter_age : "Please Enter Age",
  your_feedback_submitted : "Your Feedback Sucessfully Submitted",
  keep_our : "Keep Our", 
  clean : "Clean",
  //Newly Added
  app_version : "App Version :",
  exit_app : "Exit App",
  enter_your_text : "Enter Your Text",
  choose_image : "Choose Image",
  click_image : "Click Image",
  dear_user : "Dear User",
  location_updated : "Your Location Sucessfully Updated",
  pick_image : "PickImage",
  home_message : "Keep Our Chatrapur Clean",
  upload_image : "Please upload image",
  please_enter_number : "Please enter phoneNumber",
  please_enter_valid_info : "Please enter OTP",
  please_select_image : "Please select image",
  while_storing_image : "Oops!! there is an error while storing image",
  map : "Map",
  satelite : "Satelite",
  failed_to_insert_user: "Failed to insert user",
  please_select_c_type : "Select complaint type",
  please_enter_comment : "Please enter comment",
  comment : "Comment",
  please_select_b_type : "Select booking type",
  please_select_waste_type: "Please select booking type",
  req_veh : "Booking Type",
  select_task:"Select booking",
  confirm_to_exit : "Confirmation to exit?",
  history_t : "History of",
  please_select_all : "Please answer all questions",
  please_select_location_by_clicking : "click on red colour 'location' button and save your current location",
  please_enter_d_no : "Please enter door number",
  user_with_same_d_no_exists : "User with same door number exist",
  d_no : "Door No",
  cannot_update : "You are not allowed to update this household.Please contact admin",
  please_enter_d_no_properly : "Door number should be in alphanumeric capital letter (EX:ABCD123FE)",
  getting_this_month_report : "Please wait getting current month report",
  please_switch_location : "Please switch on your location in mobile",
  switch_on_location : "Switch on your location",
  location_permission : 'You have not given location permission for the app. so kindly give the location permission from the app',
  camera_permission : "You have not given camera permission for the app. so kindly give the camera permission from the app",
  please_assign_tag_to_you : "Please assign tags to you.",
  permission_to_acess_storage : "You have not given storage permission for the app. so kindly give the storage permission from the app",
  all : "All"








}