export default {
  notifications : "Notifications",
  mapView : "Map View",
  editDetail : "Edit Details",
  complaint : "Complaint",
  complaints : "Complaints",
  logout : "Log out",
  welcome : "Welcome",
  name : "Name",
  phoneNumber : "Phone Number",
  email : "Email",
  address : "Address",
  select_your_ward : "Select your area",
  select_your_type : "Select your type",
  update_current_location: "Update current location",
  submit: "Submit",
  details : "Details",
  loading : "Loading ...",
  take_picture : "Take Picture",
  edit_picture : "Edit Picture",
  type_of_complaint : "Type of complaint",
  message : "Message",
  send : "Send",
  send_otp : "Send OTP",
  confirm : "Confirm",
  complaint_message : "Complaint Message",
  confirmation_code : "Confirmation Code",
  firstName_lastName : "FirstName LastName",
  search : "Search",
  select_language : "Select Language",
  we_shall_contact_you_soon: "We shall contact you soon.",
  please_enter_complaint_message: "Please enter complaint message",
  alert_c : 'ALERT',
  ok_c : "OK",
  cancel : "Cancel",
  save : "save",
  please_grant_location_permission : "Please grant location permission",
  please_enter_10_digit_phonenumber : "Please enter valid 10 digit phoneNumber",
  please_enter_valid_info : "Please enter valid info",
  please_enter_valid_phoneNumber : "Please enter valid phonenumber",
  please_enter: "Please enter",
  message_sent_successfully: "Message sent successfully",
  your_notifications: "Your Notifications",
  register_your_complaint: "Register Your Complaint",
  image_loading : "Image Loading",
  please_wait_until_image_is_loaded: "Please wait until photo is loaded",
  oops_there_is_an_error_while_getting_image_url: "Oops!! there is an error while getting image url",
  oops_there_is_an_error_whie_storing_image: "Oops!! there is an error while storing image",
  your_complaints_list : "Your complaints list",
  add_complaint : "Add Complaint",
  your_complaints : "Your complaints",
  about_us : "About Us",
  near_shiv_temple: "Near shiva temple",
  close_c : "Close",
  delete_c : "DELETE",
  otp_sent : "OTP Sent",
  resend_otp : "Resend Otp",
  an_initiative_by : "An initiative by",
  deleting_notif : "Deleting Notification",
  fetching_notification : "Fetching Notification",
  enter_mobile_number : "Enter Your Mobile Number",
  we_have_sent_otp_on : "OTP has been sent to the registered mobile number",
  reeenter_number : "Re enter number",
  see_nearby_garbage_vehicles : "See nearby garbage vehicle",
  we_will_access_your_location : "We will access your location",
  allow_c : "ALLOW",
  ward: "Ward",
  comissioner : "Municipal Commissioner",
  mayor : "Chairperson",
  otp : "OTP",
  collector : "District Collector",
  adm : "Additional District Magistrate",
  executive_officer : "Executive Officer",
  please_confirm : "Please Confirm",



  // types of garbage
  garbage_dump : "Garbage dump",
  garbage_vehicle_Not_arrived : "Garbage Vehicle not arrived",
  dustbins_not_cleaned: "Dustbins not cleaned",
  sweeping_not_done: "Sweeping not done",
  dead_animal: "Dead animal",
  public_toilets_cleaning: "Public toilets cleaning",
  public_toilets_blockage: "Public toilets blockage",
  no_water_supply_in_public_toilets: "No water supply in public toilets",
  no_electricity_in_public_toilets: "No electricity in public toilets",
  others: "Others",
  drain_not_cleaned : "Drain not cleaned",


  tasks : "Tasks",
  your_tasks : "Your tasks",
  view_in_map : "View In Map",
  done : "Done",
  not_my_work : "Not my work",
  close : "Close",
  status : "Status",
  creation_date : "Creation Date",
  task_type : "Task Type",
  please_enter_your_comment : "Please enter your comment",
  acknowledgement : "Acknowledgment",
  boardUsers : "Onboard Residents",
  duty_on_c : "DUTY ON",
  duty_off_c : "DUTY OFF",
  agent_is_not_approved : "Safai Mitra profile not approved, please contact Admin.",
  duty_is_off: "Duty is off !!!",
  yes_c : "YES",
  no_c : "NO",
  segregation : "Segregation",
  this_is_an_agent_app : "This is an agent app",
  home : "Home",
  userId : "User Id",
  survey : "Survey",
  work_in_progress : "Work in progress",
  history : "History",
  assignments: "Assignments",
  // acknowledgement : "Acknowledgements",
  notif_welcome_msg : "Don't throw garbage all around. Use dustbin. Your city is your own house. Clean city, Clean house.",

  please_grant_location_permission_c : "PLEASE GRANT LOCATION PERMISSION",
  error_in_getting_current_location: "Error in getting current location",
  error_in_getting_location_please_set_location_in_map : "Error in getting location. Please set location in map.",
  or_c : "OR",
  select_location : "Select Location",
  select_location_from_map : "Select Location from map",
  select_current_location : "Select current location",
  user_onboarded_successfully : "User onboarded successfully",
  user_with_same_number_exists : "User with same number exists",
  failed_to_get_location : "Failed to get location",
  refresh : "Refresh",
  saathi_duty_is_off : "Safai Mitra duty is off",
  please_select_a_location: "Please select a location",
  currently_you_donot_have_any_assignments : "Currently you donot have any assignments",
  currently_you_donot_have_any_notifications : "Currently you donot have any notifications",
  currently_your_history_list_is_empty : "Currently your history list is empty",
  
  

  allow: "Allow",
  auto_start_permission: "Auto start Permission",
  // auto_start_message: "Please allow binimise to access auto start permission",
  auto_start_message: "Allow Auto Start Permission Access To Sughghar Jagdalpur",
  // permission_request: "Please allow binimise to access Access Activity Recognition, Coarse Location Service, Fine Location services and File Manager and Camera",
  permission_request: "You need to grant access to ACTIVITY RECOGNITION, Coarse Location Service, Fine Location services and File Manager and Camera",
  editYourDetail : "Edit Your Details",

  you_are_offline: "You are offline !!!",
  image_loaded_successfully: "Image loaded successfully",
  currently_you_donot_have_daily_images: "You have not uploaded any images today",
  fetching_images: "Fetching images",
  images : "Images",
  please_give_permission_for_background_sync : "Please give permission for background sync",
  view_more : "View More",
  noOfPersons: "No of persons",
  present: "Present",
  absent: "Absent",
  fetching_tasks: "Fetching tasks",
  state: "State",
  see_route: "See Route",
  no_attendance_found_for_this_date : "No attendance found for this date",
  raised_by : "Raised By",
  signup_to_continue: "Sign up to continue",
  updateCitizen: "Update Citizen",
  updateResident: "Update Resident",
  search_user_by_phoneNumber: "Search by phonenumber",
  update_details : "Update Details",
  no_user_with_this_number_exists : "No user with this number exists",
  failed_to_update_citizen : "Failed to update citizen",
  user_detail_updated_successfully : "User detail updated successfully",
  donot_have_phoneNumber_press_here : "Donot have phone number? Press here.",
  please_enter_name : "Please enter name",
  no_user_with_this_name_exists : "No user wth this name exists",
  search_user_by_name : "Search user by name",
  toiletStatus: "Toilet Status",
  safaAppInstalled : "Safa App Installed",
  fiveMeterAwareness : "Five Meter Awareness",
  holdingNo : "Holding No",
  houseOwner : "House",
  houseType : "House Type",
  drainImage : "Drain Image",
  deSludgingDate : "Desludging Date",
  unknown : "Unknown",
  blue : "Blue",
  green : "Green",
  own : "Own",
  Rent : "Rent",
  kachcha : "Kachcha",
  pakka : "Pakka",
  first_floor: "First floor",
  second_floor: "Second floor",
  third_floor: "Third floor",
  tin: "Tin",
  twinPit : "Twin Pit",
  septicTank : "Septic Tank",
  drain : "Drain",
  both : "Both",
  typeOfToilet : "Type of toilet",
  dustBinStatus : "Dustbin status",
  waterSupply : "Water Supply",
  dustBinColor : "Dustbin Color",
  please_enter_15_digit_aadharNumber : "Please enter 12 digit aadhar number",
  phd : "Phd",
  aadharNumber : "Aadhar Number",
  supplyType : "Supply Type",
  please_select_supplyType : "Please enter supply type",
  please_select_deSludgingDate : "Please enter desulging date",
  location_request : "Please Allow Sughghar Jagdalpur To Access  Location Services",
  attendance : "Attendance",
  qr_code_scan : "Qrcode Scanned Sucessfully!",
  one_or_more : "Add one or more photos",
  boardCheckpoints : "Add Checkpoint",
  updateCheckpoint : "Update Checkpoint",
  update_location : "Update Location",
  reset : "Reset",
  _onBoardResidents: "onBoardResidents",
  preview_details : "Preview Details",
  no_survey_assigned : "No Survey Assigned",
  get_user_details  : "get user details by",
  ctpt: "CTPT",
  ct_pt: "CT/PT",
  landmark : "Landmark",
  constructionStatus : "Construction Status",
  maintainedBy : "Maintained By",
  contactNo : "Contact No",
  drainage : "Drainage",
  area : "Area",
  chargesType : "Charges Type",
  toiletSeats : "Toilet Seats",
  signageBoard : "Signage Board",
  spaceForAdvertisement : "Space For Advertisement",
  beautificationTypes : "Beautification Types",
  electricity : "Electricity",
  mirror : "Mirror",
  washbasin : "washbasin",
  handwash : "Handwash",
  toiletCleaner : "Toilet Cleaner",
  please_take_outside_image : "Please take outside image",
  please_take_inside_image : "Please take inside image",
  updated_successfully : "Updated Successfully",
  payments : "Payments",
  payment : "Payment",
  updatePlace : "Update Place",
  paymenttype : "Payment Type",
  Go_To_Payment: "Goto Payments",
  would_you_like_to_continue : "would you like to continue?",
  add_User:"Add User",

  update : "Update",
  add_user : "Add User",
  please_enter_mobileNumber_or_aadhar_Number : "Please enter mobile or aadharNumber",
  bookings:"Bookings",

  isWasteCollected:"is waste collected?",
  isWasteSeggregated : "is waste segregated?",
  unable_to_find_users : "No households and commercials near by",
  acknow_user : "Acknowledge user",
  scan_qr : "Scan QR",
  unable_to_find_ctpt:"Unable to find Ctpt",
  acknow_ctpt:"Acknowledge CTPT",
  checkpoint_onboarded_successfully:"Checkpoint Onboarded Sucessfully",
 //hn
  boardCommercial :"Onboard Commercial",
  boardCtpt : "Onboard CTPT",
  updatectpt : "Update CTPT",
  please_take_image : "Please Take Image",
  commercial_onboarded_successfully : "Commercial onboarded successfully",
//
  click_below:"Click below to select your area",
  click_to_change : "Click On Map To Change Location",
  click_to_select :"Click On Map To Select Location",
  click_to_attach :"Click To Attach Photo",
  search_user_qr:"Search User By Qr",
  search_commercial_qr : "Search Commercial By Qr",
  no_user_with_this_qr_exists:"No User With This Qr Exists",
  user_with_same_qr_exists : "User with same qr exists",
  check_with_same_qr_exists : "Checkpoint with same qr exists",
  ctpt_with_same_qr_exists : "CTPT with same qr exists",
  scanned_qr_for:"Scanned Qr For ",
  qr_code_attached:"Qr Code Attached Sucessfully",
  location_sucess:"Location Sucessfully Updated..",
  take_image : "Take Image",
  retake_image : "Retake Image",
  click_below_t:"Click Below To Select Your Checkpoint",
  is_waste:"isWasteSeggregated",
  is_waste_c: "isWasteCollected",
  switch_on_duty_c : "Safai Mitra profile not approved, Please contact Admin and then switch on your duty",
  switch_on_duty : "Please switch on your duty",
  close_m : "Close Map",
  
  update_qr:"Update qr",
  scanned_val :"Scanned Value",
  close_map :"Close Map",
  please_take_image_of_house : "Photo of house",
  household : "Households",
  checkpoint : "Checkpoints",
  not_belongs_to_ward : "This user is not belongs to your ward..!",
  otp_sent_to : "The OTP has been sent to your Mobile Number",
  dear_user : "Dear User",
  ack_data_stored: "Acknowledgement Data Stored Sucessfully",
  location_captured : "Location Captured Sucessfully",
  location_updated : "Location Updated Sucessfully",
  duty_hours : "Duty Hours(HH:MM)",
  photos : "Photos",
  route : "Route",
  garbage_c:"Garbage Collected",
  garbage_nc:"Garbage not Collected",
  no_data_found : "No data found for this date",
  history_details : "History Details",
  go_to_history : "Go To History",
  userprofile : "User Profile",
  editprofile : "Edit Profile",
  commercial : "Commercial",
  updateCommercial : "UpdateCommercial",
  waste:"Waste",
  pending_amount : "Pending Amount",
  advance_amount : "Advance Payment",
  select_your_payment: "Select Your Payment",
  payment_mode : "Select Your Paymentmode",
  upi : "UPI",
  cash : "CASH",
  payment_added : "Payment Added Sucessfully",
  go_to_ack : "Go To Acknowledgement",
  go_to_payment : "Go To Payment",
  add_payment : "Add Payment",
  places : "Places",
  prior_to_work :  "Prior to Work",
  complaint_type : "Complaint Type",
  sk_name : "Shopkeeper Name",
  sh_name : "Shop Name",
  show_navigation : "Navigation",
  fuel_management : "Fuel Management",
  new_request : "New Request",
  click_below_v : "Click below to select vehicle",
  fuel_quantity : "Fuel quantity",
  en_fuel_quantity : "Enter fuel quantity",
  select_your_vehicle : "Select vehicle",
  add_request : "Fuel request",
  fuel_detail_added_successfully : "Fuel details added successfully",
  please_select_vehicle : "Please select vehicle",
  filter_c: "Filter",
  vehicle_id : "Vehicle Id",
  date : "Date",
  quantity : "Quantity",
  saathi : "Saathi",
  all : "All",
  online_saathi : "Online Saathi",
  offline_saathi : "Offline Saathi",
  res_ack : "Residents Acknowledged",
  com_ack : "Commercials Acknowledged",
  res_onBoard : "Residents Onboarded",
  com_onBoard : "Commercials Onboarded",
  select_staff : "Select Staff",
  please_take_image_of_saathi : "Please Take Image Of Staff",
  please_select_staff : "Please Select Staff",
  registartion : "Registration",
  onboard : "Onboard",
  please_enter_details : "Please Enter Details",
  saathi_exist : "Staff With Same PhoneNumber Already Exist",
  onboard_staff : "Onboard Staff",
  update_staff : "Update Staff",
  select_saathi : "Select Staff",
  enter_your_text : "Enter Your Text Here..",
  duty_on : "Duty On",
  duty_off : "Duty Off",
  current_status : "Current Status",
  attendance : "Attendance",
  total_hours : "Total Hours",
  reports : "Reports",
  saathi_attendance : "Staff Attendance",
  staff_is_not_approved : "Staff is not approved",
  view_staff : "View Staff",
  delete : "Delete",
  father_name : "Father Name",
  please_enter_userId : "Please Enter UserId",
  please_enter_name : "Please Enter Name",
  please_enter_number : "Please Enter PhoneNumber",
  please_enter_image : "Please Click Photo",
  view : "View",
  edit : "Edit",
  go_to_viewstaff : "Go To Viewstaff",
  please_take_image_properly : "Please Take Image Properly",
  data_updated : "Data Updated",
  spot_fine :"Spot fine",
  enter_comment : "Enter Comment",
  comment : "Comment",
  sync_photo_locally: "Sync photo locally",
  please_enter_father : "Please Enter FatherName",
  edit_staff : "Edit Staff",
  staff_details : "Staff Details",
  staff_reports : "Staff Reports",
  no_staff_assign : "No Staff Assign To You",
  image : "Image",
  post_spotfine : "Post Spotfine",
  assigned_spotfine : "Assigned Spotfine",
  please_upload_image : "Please upload image",
  please_select_area : "Please select area",
  please_enter_comment : "Please enter comment",
  back : "Back",
  history_t : "History Of  ",
  issupervisor : "isSupervisor",
  supervisor_name : "Supervisor Name",
  staff : "Assigned Staff",
  type : "Type",
  please_enter_userid : "Please enter userId",
  please_enter_father_name: "Please Enter Father Name",
  store_image_of_staff: "Store Images Of Staff",
  all_images_stored : "Stored Images Of All Staff",
  not_available : "Not Available",
  in_time_s : "IN TIME SELFIE",
  out_time_s : "OUT TIME SELFIE",
  please_enter_valid_otp : "Please enter valid OTP", //add from here
  press_button : "Press the button to update the app:",
  update_app : "Update App",
  error_while_capturing_image : "Oops!! there is an error while capturing image",
  app_version : "App version :",
  attendance_type : "Attendace type",
  please_select_type : "Please select attendance type",
  image_added_sucessfully : "Image added sucessfully",
  supervisor : "Supervisor",
  failed_to_mark_attendance : "Failed to mark attendance",
  self_attendace_marked : "Face attendance not required for supervisor !!!",
  matching_face : "Matching Face !!!",
  no_face_matched : "No face matched",
  no_saathi_data_fetched : 'No saathi data fetched !!!',
  failed_to_recognize_face : "Failed to recognize face",
  manual_attendance : "Manual Attendance",
  failed_to_capture_image : "Failed to capture image",
  no_face_found : "No face found",
  please_blink_your_eyes : "Please blink your eyes",
  please_come_closer_to_camera : "Please come closer to camera",
  please_take_intime_selfie : "Please take inTime attendance",
  intime_selfie_already_taken_for_this_saathi : "Intime attendance is already taken for this staff ",
  failed_to_get_saathiList : "Failed to get saathis",
  get_list : "Get Staff",
  failed_to_store_data : "Failed to store data",
  intime_attendance_already_taken_through_face_attendance : "Intime Attendance Already Taken Through Face Attendace.",
  intime_attendance_already_taken_through_manual_attendance : "Intime Attendance Already Taken Through Manual Attendace.",
  please_take_intime_attendance : "Please Take Intime Attendance.",
  outtime_attendance_already_taken_through_face_attendance : "Outtime Attendance Already Taken Through Face Attendace.",
  outtime_attendance_already_taken_through_manual_attendance : "Outtime Attendance Already Taken Through Manual Attendace.",
  saving_attendance : "Saving Attendance",
  getting_address_of_current_location : "Getting Adress Of Your Location",
  saving_data : "Saving Data",
  getting_staff : "Getting Staff",
  click_on_get_staff_to_getData : "Click On Refresh To Get StaffData",
  you_are_offline: "You are offline.Please switch on network",
    location_permission : 'Please check location in your phone and select "Allow all the time" to close this modal',
    camera_permission : "Please give permission to access your camera",
    assigned_tasks : "Assigned Tasks",
    fetching_tasks : "Fetching Spotfine",
    no_wards_assigned : "No area assigned to you",
    please_switch_location : "Please switch on your location in mobile",
    switch_on_location : "Switch on your location",
    getting_users : "Getting households and commercials"

  // Getting staff data
  






}