export default {
  notifications: "सूचनाएँ",
  mapView: "नक्शा दृश्य",
  editDetail: "विवरण संपादित करें",
  complaint: "शिकायतें",
  logout: "लोग आउट",
  welcome: "स्वागत है",
  name: "नाम",
  phoneNumber: "फ़ोन नंबर",
  email: "ईमेल",
  address: "पता",
  select_your_ward: "अपनी वार्ड का चयन करें",
  update_current_location: "वर्तमान स्थान अपडेट करें",
  submit: "प्रस्तुत करें",
  details: "विवरण",
  loading: "लोड हो रहा है...",
  loading_com: "शिकायतों को लोड किया जा रहा है",
  loading_book: "बुकिंग्स लोड हो रही हैं",
  take_picture: "तस्वीर लें",
  edit_picture: "तस्वीर संपादित करें",
  type_of_complaint: "शिकायत का प्रकार",
  message: "संदेश",
  send: "भेजें",
  send_otp: "OTP भेजें",
  confirm: "पुष्टि करें",
  complaint_message: "शिकायत संदेश",
  confirmation_code: "पुष्टि कोड",
  firstName_lastName: "पहला नाम अंतिम नाम",
  search: "खोजें",
  select_language: "भाषा बदलें",
  we_shall_contact_you_soon: "आपकी शिकायत सफलतापूर्वक दर्ज की गई है",
  we_shall_contact_you_soon_T: "आपका कार्य सफलतापूर्वक दर्ज किया गया है",
  please_enter_complaint_message: "कृपया शिकायत संदेश दर्ज करें",
  alert_c: 'चेतावनी',
  ok_c: "ठीक है",
  cancel: "रद्द करें",
  save: "सहेजें",
  please_grant_location_permission: "कृपया स्थान अनुमति प्रदान करें",
  please_enter_10_digit_phonenumber: "कृपया वैध 10 अंकों का फोन नंबर दर्ज करें",
  please_enter_valid_info: "कृपया वैध जानकारी दर्ज करें",
  please_enter_valid_phoneNumber: "कृपया वैध फोन नंबर दर्ज करें",
  please_enter: "कृपया दर्ज करें",
  message_sent_successfully: "संदेश सफलतापूर्वक भेजा गया",
  your_notifications: "आपकी सूचनाएं",
  register_your_complaint: "अपनी शिकायत दर्ज करें",
  image_loading: "छवि लोड हो रही है",
  please_wait_until_image_is_loaded: "कृपया फोटो लोड होने तक प्रतीक्षा करें",
  oops_there_is_an_error_while_getting_image_url: "ऊप्स!! छवि URL प्राप्त करते समय त्रुटि हुई",
  oops_there_is_an_error_whie_storing_image: "ऊप्स!! छवि संग्रहण करते समय त्रुटि हुई",
  your_complaints_list: "आपकी शिकायतों की सूची",
  add_complaint: "शिकायत जोड़ें",
  your_complaints: "आपकी शिकायतें",
  about_us: "हमारे बारे में",
  landmark: "सीमांत",
  near_shiv_temple: "शिव मंदिर के पास",
  close_c: "बंद करें",
  delete_c: "हटाएं",
  otp_sent: "OTP भेजा गया",
  an_initiative_by: "एक पहल",
  deleting_notif: "सूचना हटाई जा रही है",
  fetching_notification: "सूचना प्राप्त की जा रही है",
  notif_welcome_msg: "गंदगी यहाँ-वहाँ न मारें। कूड़ादानी का उपयोग करें। हमारा शहर हमारा खुद का घर है। साफ शहर, साफ घर।",
  enter_mobile_number: "अपना मोबाइल नंबर दर्ज करें",
  we_have_sent_otp_on: "हमने OTP भेजा है",
  reeenter_number: "फिर से नंबर दर्ज करें",
  resend_otp: "OTP फिर से भेजें",
  see_nearby_garbage_vehicles: "नजदीकी कूड़ा वाहन देखें",
  we_will_access_your_location: "हम आपका स्थान प्राप्त करेंगे",
  allow_c: "अनुमति दें",
  ward: "वार्ड",
  comissioner: "नगर आयुक्त",
  mayor: "अध्यक्ष",
  otp: "OTP",
  collector: "जिला कलेक्टर",
  adm: "अतिरिक्त जिला मजिस्ट्रेट",
  executive_officer: "कार्यकारी अधिकारी",
  please_confirm: "कृपया पुष्टि करें",
  for_any_query_call_on_this_number: "किसी भी प्रश्न के लिए इस नंबर पर कॉल करें",
  call: "कॉल",
  sub_collector: "उप कलेक्टर",
  no_active_complaints: "कोई सक्रिय शिकायत नहीं !!!",
  no_complaints_message: "आपके द्वारा कोई सक्रिय शिकायत नहीं है। अपने क्षेत्र की शिकायत करना शुरू करें।",
  places: "स्थान",
  register_your_complaint: "अपनी शिकायत दर्ज करें",
  mapViewFilters: "नक्शा दृश्य फ़िल्टर",
  vehicles: "वाहन",
  park: "पार्क",
  hospital: "अस्पताल",
  dumping_point: "कचरा फैलाने का स्थान",
  toilet: "शौचालय",
  signup_to_continue: "जारी रखने के लिए साइन अप करें!!!",
  editYourDetail: "अपना विवरण संपादित करें",
  places_around_you: "आपके आसपास के स्थान",
  no_places_yet: "अभी तक कोई स्थान नहीं मिला।",
  no_places_message: "आपके क्षेत्र में कोई स्थान नहीं मिला है",
  placesFilter: "स्थान फ़िल्टर",
  filter_c: "फ़िल्टर",
  save_c: "सहेजें",
  please_enter_complaint_typesOfcomplaint: "कृपया शिकायत के प्रकार का चयन करें",
  view_more: "और देखें",
  complaint_id: "शिकायत आईडी",
  image: "छवि",
  message: "संदेश",
  garbage_dump: "कचरा ढेर",
  garbage_vehicle_Not_arrived: "कचरा वाहन नहीं आया",
  dustbins_not_cleaned: "डस्टबिन सफाई नहीं हुई",
  sweeping_not_done: "सफाई नहीं हुई",
  dead_animal: "मृत पशु",
  public_toilets_cleaning: "सार्वजनिक शौचालय सफाई",
  public_toilets_blockage: "सार्वजनिक शौचालय ब्लॉकेज",
  no_water_supply_in_public_toilets: "सार्वजनिक शौचालयों में पानी की आपूर्ति नहीं",
  no_electricity_in_public_toilets: "सार्वजनिक शौचालयों में बिजली नहीं",
  others: "अन्य",
  drain_not_cleaned: "नाली सफाई नहीं हुई",
  please_grant_location_permission_c: "कृपया स्थान अनुमति प्रदान करें",
  error_in_getting_current_location: "वर्तमान स्थान प्राप्ति में त्रुटि",
  error_in_getting_location_please_set_location_in_map: "स्थान प्राप्ति में त्रुटि। कृपया मानचित्र में स्थान सेट करें।",
  or_c: "या",
  select_location: "स्थान चुनें",
  select_location_from_map: "मानचित्र से स्थान चुनें",
  select_current_location: "वर्तमान स्थान चुनें",
  add_task: "कार्य जोड़ें",
  requestVehicle: "वाहन का अनुरोध",
  request_vehicle: "वाहन का अनुरोध",
  your_requests: "आपके अनुरोध",
  no_active_requests: "कोई सक्रिय अनुरोध नहीं",
  no_requests_message: "आपके द्वारा कोई सक्रिय अनुरोध नहीं है। आप अपने स्थान पर कचरा वाहन का अनुरोध कर सकते हैं",
  please_enter_request_vehicle_message: "कृपया संदेश दर्ज करें",
  please_enter_typesOfRequestVehicle: "कृपया अनुरोध वाहन के प्रकार का चयन करें",
  request_your_vehicle: "अपने वाहन का अनुरोध करें",
  type_of_request_vehicle: "अनुरोध वाहन का प्रकार",
  request: "अनुरोध",
  request_vehicle_note: "नोट: अनुरोधित वाहनों पर शुल्क लिया जाएगा",
  please_select_waste_type: "कृपया कचरे का प्रकार चुनें",
  delete: "हटाएं",
  domestic_waste: "घरेलू\nकचरा",
  water_tank: "पानी\nटैंक",
  cesspool_tank: "सेसपूल\nकचरा",
  party_waste: "पार्टी\nकचरा",
  commercial_waste: "वाणिज्यिक\nकचरा",
  construction_waste: "निर्माण\nकचरा",
  description: "विवरण",
  enter_your_suggestion: "अपनी सुझाव दें",
  suggestion: "सुझाव",
  mark_it_home_address: "इसे घर का पता चिह्नित करें",
  segregated_waste_throw: "1. क्या आप अपने एकत्रित कचरे को विभाजित करते हैं (गीला और सूखा)?",
  searching_nearest_publicToilet: "2. क्या आप निकटतम सार्वजनिक शौचालय को गूगल पर कैसे खोज सकते हैं?",
  neighbourhood_area: "3. क्या आपको अपने पड़ोस क्षेत्र को हमेशा साफ रखने में समस्या होती है?",
  home_composting: "4. क्या आप घरेलू कॉम्पोस्टिंग के बारे में जानते हैं?",
  your_age: "5. आपकी आयु क्या है?",
  municipal_corporation: "नगर निगम",
  municipal_council: "नगर परिषद",
  history: "इतिहास",
  contactUs: "हमसे संपर्क करें",
  notice_board: "सूचना बोर्ड",
  track_garbageVan: "कचरा वैन को ट्रैक करें",
  garbageVan: "कचरा वैन",
  toilet_Locator: "शौचालय लोकेटर",
  toilets: "शौचालय",
  community: "समुदाय",
  payments: "भुगतान",
  update_account: "आपने अपने खाता को सफलतापूर्वक अपडेट किया है।",
  create_account: "आपने सफलतापूर्वक खाता बनाया है।",
  share: "शेयर",
  contact_us: "संपर्क करें",
  create_new_complaint: "नई शिकायत दर्ज करें",
  create_new_booking: "नई बुकिंग बनाएं",
  add_photo_or_video: "फोटो या वीडियो जोड़ें",
  click_to_attach: "फोटो जोड़ने के लिए क्लिक करें",
  booking_type: "बुकिंग का प्रकार",
  booking_date: "बुकिंग तारीख",
  quantity: "मात्रा",
  price: "मूल्य",
  proceed: "आगे बढ़ें",
  please_select_bookingDate: "कृपया बुकिंग तारीख चुनें",
  booking_confirmation: "बुकिंग पुष्टि",
  pay_now: "अभी भुगतान करें",
  cash_on_delivery: "कैश ऑन डिलिवरी",
  _tags: "टैग",
  prefered_lan: "पसंदीदा भाषाएँ",
  _profile: "प्रोफ़ाइल",
  no_history_found_for_this_date: "इस तारीख के लिए कोई इतिहास नहीं मिला",
  bookings_not_available: "आपके लिए बुकिंग उपलब्ध नहीं थी। कृपया अपने व्यवस्थापक से संपर्क करें।",
  mobile_num_change: "मोबाइल नंबर बदलें",
  update: "अपडेट",
  signup: "साइन अप",
  skip: "छोड़ें",
  proceed: "आगे बढ़ें",
  houseno: "घर संख्या",
  wardnum: "वार्ड नंबर",
  tagurself: "खुद को टैग करें",
  locateme: "मुझे ढूंढें",
  settings: "सेटिंग्स",
  location: "स्थान",
  add_location: "स्थान जोड़ें",
  update_location: "स्थान अपडेट करें",
  alert: "अलर्ट",
  show_alert: "अलर्ट दिखाएं",
  show_notification: "सूचना दिखाएं",
  assigned_tags: "निर्धारित टैग",
  add_tag: "टैग जोड़ें",
add_newtag: "नया टैग जोड़ें",
ward_details: "वार्ड विवरण",
show_alerts: "अलर्ट दिखाएं",
make_my_profile_private: "मेरी प्रोफ़ाइल को निजी बनाएं",
new_booking: "नई बुकिंग",
new_complaint: "नयी शिकायत",
complaint_date: "शिकायत तिथि",
complaint_no: "शिकायत संख्या",
muncipality: "नगरपालिका",
list_of_vehicles_available: "उपलब्ध वाहनों की सूची",
enter_otp: "OTP दर्ज करें",
no_notification: "कोई सूचनाएँ नहीं",
retake: "फिर से लें",
post_complaint: "शिकायत पोस्ट करें",
select_complaint: "शिकायत का प्रकार चुनें",
select_task: "कार्य का प्रकार चुनें",
current_location: "वर्तमान स्थान",
describe_issue: "मुद्दा विवरण करें",
capture_image: "तस्वीर कैप्चर करें",
select_type: "प्रकार चुनें",
booking: "बुकिंग",
active: "सक्रिय",
assign: "निर्धारित",
close: "बंद",
_close: "बंद करें",
refresh: "रीफ़्रेश",
age: "आयु",
other_num: "अन्य नंबर",
feedback: "फ़ीडबैक",
ward_d: "वार्ड विवरण",
photos: "तस्वीरें",
navigation: "नेविगेशन",
view_n: "नेविगेशन देखें",
otp_sent_to: "OTP आपके मोबाइल नंबर पर भेजा गया है",
dear_user: "प्रिय उपयोगकर्ता",
congrats: "बधाई हो!",
Call_JMC: "JMC हेल्पलाइन पर कॉल करें",
full_name: "पूरा नाम",
mobile_num: "मोबाइल नंबर",
emailid: "ईमेल आईडी",
requestType: "अनुरोध प्रकार",
bookedOn: "बुक किया गया",
bookedFor: "पहुंचाया गया",
assignedTo: "सौंपा गया",
tId: "कार्य आईडी",
req_veh: "अनुरोधित वाहन",
taskType: "कार्य प्रकार",
ACTIVE: "सक्रिय",
ASSIGNED: "सौंपा गया",
CLOSED: "बंद",
PENDING: "अपूर्ण",
userprofile: "उपयोगकर्ता प्रोफाइल",
editprofile: "प्रोफ़ाइल संपादित करें",
area: "क्षेत्र",
attended_by: "द्वारा उपस्थित",
time: "समय",
acknowledgement: "प्राप्ति पुस्तिकरण",
segregation: "विभाजन",
no_data_found: "इस तारीख के लिए कोई डेटा नहीं मिला",
go_to_c: "कैलेंडर दिखाएं",
confirm_to_exit: "निकासी की पुष्टि करें?",
hold_on: "रुकिए!",
tag_added: "नया टैग सफलतापूर्वक जोड़ा गया!",
garbage_collected: "कचरा संग्रहित",
garbage_segregation: "कचरे का विभाजन नहीं हुआ",
garbage_picker_absent: "कचरा चुनने वाला गायब है",
unavailable: "अनुपलब्ध",
saving_complaint: "शिकायत सहेज रहा है",
command_center: "कमांड केंद्र",
please_enter_valid_otp: "कृपया मान्य OTP दर्ज करें",
keep_our_mun: "हमारा Buguda साफ रखें",
please_enter_suggerstion: "कृपया सुझाव दें",
please_enter_age: "कृपया आयु दर्ज करें",
your_feedback_submitted: "आपकी प्रतिक्रिया सफलतापूर्वक प्रस्तुत की गई है",
keep_our: "हमारा",
clean: "स्वच्छ",
app_version: "एप्लिकेशन संस्करण:",
exit_app: "ऐप बंद करें",
enter_your_text: "अपना पाठ दर्ज करें",
choose_image: "तस्वीर चुनें",
click_image: "तस्वीर लें",
dear_user: "प्रिय उपयोगकर्ता",
location_updated: "आपका स्थान सफलतापूर्वक अपडेट किया गया है",
pick_image : "छवि चुनें",
home_message : "हमारे छत्रपुर को स्वच्छ रखें",
upload_image : "कृपया छवि अपलोड करें"

} 