export default {
  notifications : "सूचनाएं",
  mapView : "नक्शा देखें",
  editDetail : "विवरण बदलें",
  complaint : "शिकायत",
  logout : "लॉग आउट",
  welcome : "स्वागत है",
  name : "नाम",
  phoneNumber : "फ़ोन नंबर",
  email : "ईमेल",
  address : "पता",
  select_your_ward : "अपने वार्ड का चयन करें",
  update_current_location: "वर्तमान स्थान अपडेट करें",
  submit: "भेजें",
  details : "विवरण",
  loading : "लोड हो रहा है",
  take_picture : "तस्वीरें ले",
  type_of_complaint : "शिकायत का प्रकार",
  message : "संदेश",
  send : "भेजें",
  edit_picture : "चित्र बदलें",
  send_otp : "OTP भेजें",
  confirm : "पुष्टि करें",
  complaint_message : "शिकायत संदेश",
  confirmation_code : "पुष्टि कोड",
  firstName_lastName : "हिमांशु राज",
  search : "ढूढें",
  select_language : "भाषा का चयन करें",
  we_shall_contact_you_soon: "हम जल्द ही आपसे संपर्क करेंगे",
  please_enter_complaint_message : "कृपया शिकायत संदेश दर्ज करें",
  alert_c : 'संदेश',
  ok_c : "ठीक है",
  cancel : "बंद करे",
  save : "सहेजें",
  please_grant_location_permission: "कृपया स्थान अनुमति प्रदान करें",
  please_enter_10_digit_phonenumber : "कृपया 10 अंकों का वैध फोन दर्ज करें",
  please_enter_valid_info : "कृपया मान्य जानकारी दर्ज करें",
  please_enter_valid_phoneNumber : "कृपया एक वैध नंबर डालें",
  please_enter: "कृपया दर्ज करें - ",
  message_sent_successfully: "संदेश सफलतापूर्वक भेजा जा चुका है",
  your_notifications: "आपकी सूचनाएं",
  register_your_complaint: "अपनी शिकायत दर्ज करें",
  image_loading: "फोटो लोड हो रहा है",
  please_wait_until_image_is_loaded: "कृपया फ़ोटो लोड होने तक प्रतीक्षा करें",
  oops_there_is_an_error_while_getting_image_url: "उफ़ !! फ़ोटो प्राप्त करते समय कोई त्रुटि है",
  oops_there_is_an_error_whie_storing_image: "उफ़ !! फ़ोटो संग्रहीत करते समय कोई त्रुटि है",
  your_complaints_list : "आपकी शिकायतों की सूची",
  add_complaint : "नई शिकायत",
  your_complaints : "आपकी शिकायतें",
  about_us : "हमारे बारे में",
  landmark : "सीमा चिन्ह",
  near_shiv_temple: "शिव मंदिर के पास",
  close_c : "बंद करे",
  delete_c : "हटाएँ",
  otp_sent : "OTP भेजा गया",
  an_initiative_by : "द्वारा एक पहल",
  fetching_notification : "सूचना ला रहा है",
  deleting_notif: "सूचना हटाना",
  mayor_name : "श्रीमती रूबी देवी",
  comissioner_name : "श्री धीरेन्द्र पासवान",
  notif_welcome_msg : "कचरा इधर-उधर न फेंके। डस्टबिन का उपयोग करें। आपका शहर आपका अपना घर है। स्वच्छ शहर, स्वच्छ घर।",
  ward : "वार्ड",
  enter_mobile_number : "अपना मोबाइल नंबर दर्ज करें",
  we_have_sent_otp_on : "हमने ओटीपी भेजा है ",
  reeenter_number : "फिर से नंबर दर्ज करें",
  resend_otp : "ओटीपी पुनः भेजें",
  please_grant_location_permission : "कृपया स्थान की अनुमति प्रदान करें",
  see_nearby_garbage_vehicles : "पास में कचरा वाहन देखें",
  we_will_access_your_location : "हम आपके स्थान पर पहुँचेंगे",
  allow_c : "अनुमति",
  comissioner : "नगर आयुक्त",
  mayor : "नगर सभापति",
  otp: "ओ.टी.पी.",
  collector : "जिलाधीश",
  adm : "अतिरिक्त जिला दंडनायक",
  executive_officer : "नगर कार्यपालक अधिकारी",
  please_confirm : "कृपया पुष्टि करें",
  for_any_query_call_on_this_number : "इस नंबर पर किसी भी प्रश्न के लिए कॉल करें",
  call : "कॉल",
  // types of garbage
  garbage_dump : "कूड़े का ढेर",
  garbage_vehicle_Not_arrived : "कचरा वाहन नहीं पहुंचा",
  dustbins_not_cleaned: "डस्टबिन की सफाई नहीं",
  sweeping_not_done: "सफाई नहीं हुई",
  dead_animal: "मृत पशु",
  public_toilets_cleaning: "सार्वजनिक शौचालय की सफाई",
  public_toilets_blockage: "सार्वजनिक शौचालय रुकावट",
  no_water_supply_in_public_toilets: "सार्वजनिक शौचालयों में पानी की आपूर्ति नहीं",
  no_electricity_in_public_toilets: "सार्वजनिक शौचालयों में बिजली नहीं",
  others: "अन्य",
  drain_not_cleaned : "नाली की सफाई नहीं हुई",
  please_grant_location_permission_c : "कृपया ध्यान से देखें",
  error_in_getting_current_location: "वर्तमान स्थान प्राप्त करने में त्रुटि",
  error_in_getting_location_please_set_location_in_map : "स्थान पाने में त्रुटि। कृपया मानचित्र में स्थान सेट करें।",
  or_c : "या",
  select_location : "स्थान चुनें",
  select_location_from_map : "मानचित्र से स्थान का चयन करें",
  select_current_location : "वर्तमान स्थान का चयन करें",
  feedback:"",
  enter_your_suggestion : "अपना सुझाव दर्ज करें",
  add_task: "कार्य जोड़ें",
  cesspool_tank: "सेसपूल\nअपशिष्ट",
  commercial_waste: "वाणिज्यिक\nअपशिष्ट",
  complaint_id: "शिकायत आईडी",
  construction_waste: "निर्माण\nअपशिष्ट",
  delete: "हटाएं",
  description: "विवरण",
  domestic_waste: "घरेलू कचरा",
  dumping_point: "डंपिंग प्वाइंट",
  editYourDetail: "अपना विवरण संपादित करें",
  filter_c: "फ़िल्टर",
  hospital: "अस्पताल",
  image: "छवि",
  mapViewFilters: "मानचित्र दृश्य फ़िल्टर",
  no_active_complaints: "कोई सक्रिय शिकायत नहीं !!!",
  no_active_requests: "कोई सक्रिय अनुरोध नहीं है",
  no_complaints_message: "आपके द्वारा कोई सक्रिय शिकायत दर्ज नहीं की गई है। अपने क्षेत्र की शिकायत दर्ज करना शुरू करें।",
  no_places_message: "आपके क्षेत्र में कोई जगह नहीं मिली",
  no_places_yet: "कोई स्थान नहीं मिला।",
  no_requests_message: "आपसे कोई सक्रिय अनुरोध नहीं है। आप अपने स्थान पर कचरा वाहन का अनुरोध कर सकते हैं",
  park: "पार्क",
  party_waste: "पार्टी\nअपशिष्ट",
  places: "प्रसिद्ध स्थान",
  placesFilter: "स्थान फ़िल्टर",
  places_around_you: "आपके आस-पास के स्थान",
  please_enter_complaint_typesOfcomplaint: "कृपया शिकायत का प्रकार चुनें",
  please_enter_request_vehicle_message: "कृपया संदेश दर्ज करें",
  please_enter_typesOfRequestVehicle: "कृपया अनुरोध वाहन का प्रकार चुनें",
  please_select_waste_type: "कृपया अपशिष्ट प्रकार चुनें",
  request: "निवेदन",
  requestVehicle: "अनुरोध वाहन",
  request_vehicle: "अनुरोध वाहन",
  request_vehicle_note: "नोट: अनुरोधित वाहनों पर शुल्क लगाया जाएगा",
  request_your_vehicle: "अपने वाहन का अनुरोध करें",
  save_c: "सहेजें",
  signup_to_continue: "जारी रखने के लिए साइन अप करें!!!",
  sub_collector: "उप कलेक्टर",
  toilet: "शौचालय",
  type_of_request_vehicle: "अनुरोध वाहन का प्रकार",
  vehicles: "वाहनों",
  view_more: "और देखो",
  water_tank: "पानी की टंकी",
  your_requests: "आपके अनुरोध",
  commissioner : "नगर आयुक्त",
  assigned_to : "सौंपा गया",
  suggestion: "सुझाव",
  mark_it_home_address : "इसे घर के पते के रूप में चिह्नित करें",
  feedback:"प्रतिक्रिया",
  segregated_waste_throw:"1.क्या आप अपने एकत्रित कचरे को अलग-अलग कचरा (गीला और सूखा) देते हैं?",
  searching_nearest_publicToilet:"2.क्या आप जानते हैं कि आप Google पर निकटतम सार्वजनिक शौचालय कैसे खोज सकते हैं?",
  neighbourhood_area:"3.क्या आप अपने आस-पड़ोस के क्षेत्र को हमेशा साफ-सुथरा पाते हैं?",
  home_composting:"4. क्या आप घरेलू खाद के बारे में जानते हैं?",
  your_age:"5. आपकी उम्र क्या है?",
  municipal_corporation : "",
  
  history : "इतिहास",
  booking: "बुकिंग",
  contactUs : "",
  notice_board : "",
  track_garbageVan : "कचरा गाड़ी को ट्रैक करें",
  garbageVan : "कचरा गाड़ी",
  toilet_Locator : "टॉयलेट लोकेटर",
  toilets : "टॉयलेट",
  community : "",
  payments : "Payments",
  update_account : "आपने अपना खाता सफलतापूर्वक अपडेट कर लिया है।",
  create_account : "आपने सफलतापूर्वक एक खाता बना लिया है।",
  share : "",
  contact_us : "संपर्क करें",
  create_new_complaint : "नई शिकायतें दर्ज कराएं",
  add_photo_or_video : "फ़ोटो या वीडियो जोड़ें",
  click_to_attach : "फ़ोटो संलग्न करने के लिए क्लिक करें",
  create_new_booking : "नई बुकिंग बनाएँ",
  booking_type : "बुकिंग के प्रकार",
  booking_date : "बुकिंग की तारीख",
  quantity : "परिमाण",
  price : "दाम",
  proceed : "चलना",
  please_select_booking_date : "कृपया बुकिंग दिनांक का चयन करें",
  booking_confirmation : "बुकिंग की पुष्टि",
  pay_now : "अब भुगतान करें",
  cash_on_delivery : "कैश ऑन डिलीवरी",
  _tags:"टैग",
  prefered_lan :"भाषा को तरजीह दी",
  _profile :"रूपरेखा",
  no_history_found_for_this_date : "इस तिथि के लिए कोई इतिहास नहीं मिला",
  bookings_not_available : "बुकिंग आपके लिए उपलब्ध नहीं थी। कृपया अधिक जानकारी के लिए अपने व्यवस्थापक से संपर्क करें..",
  mobile_num_change :"मोबाइल नंबर बदलें",
  update : "अपडेट",
  signup : "साइन अप",
  skip : "छोड़ें",
  proceed : "आगे बढ़ना",
  emailid: "ईमेल आईडी",
  houseno : "माकन नंबर",
  wardnum :"वार्ड संख्या",
  tagurself : "स्वयं को टैग करें",
  locateme : "मुझे खोजें",
  settings : "समायोजन",
  location :"स्थान",
  add_location :"स्थान जोड़ना",
  alert :"अलर्ट",
  show_alert:"शोअलर्ट",
  show_notification :"अधिसूचना दिखाएं",
  assigned_tags : "असाइन किया गया टैग",
  add_tag :"टैग जोड़ो",
  add_newtag : "नयाटैग जोड़ें",
  ward_details : "वार्ड विवरण",
  show_alerts : "अलर्ट दिखाएं",
  make_my_profile_private : "मेरी प्रोफ़ाइल को निजी बनाएं",
  new_booking :"नई बुकिंग",
  new_complaint : "नई शिकायत",
  complaint_date : "शिकायत तिथि",
  complaint_no  :"शिकायत संख्या",
  muncipality : "नगर पालिका",
  list_of_vehicles_available:"पर उपलब्ध वाहनों की सूची",
  enter_otp : "ओटीपी दर्ज करें",
  municipal_council : "नगर पालिका परिषद",
  age:"आयु",
  other_num:"अन्य संख्याएँ",
  ward_d:"वार्ड विवरण",
  no_notification:"कोई सूचनाएं नहीं",
  refresh:"ताज़ा करना",
  retake:"रीटेक",
  post_complaint:"शिकायत पोस्ट करें",
  select_complaint:"शिकायत प्रकार का चयन करें",
  current_location:"वर्तमान स्थान",
  describe_issue:"समस्या का वर्णन करें",
  capture_image:"छवि कैप्चर करें",
  select_type:"प्रकार चुनें",
  booking : "बुकिंग के",
  active:"सक्रिय",
  assign:"सौंपा गया",
  close:"बंद किया हुआ",
  _close:"बंद किया हुआ",
  feedback:"प्रतिक्रिया",
  ward_d:"वार्ड विवरण",
  select_task:"कार्य प्रकार का चयन करें",
  please_select_bookingDate : "कृपया बुकिंग तिथि चुनें",
  we_shall_contact_you_soon_T: "आपका कार्य सफलतापूर्वक पंजीकृत है",
  photos:'तस्वीरें',
  navigation:"मार्गदर्शन",
  view_n:"नेविगेशन देखें",
  otp_sent_to : "आपके मोबाइल नंबर पर ओटीपी भेज दिया गया है",
  dear_user : "प्रिय उपयोगकर्ता",
  congrats : "बधाई!",
  Call_JMC : "कॉल JMC helpline",
  full_name : "पूरा नाम",
  mobile_num : "मोबाइल नंबर",
  requestType : "अनुरोध का प्रकार",
  bookedOn : "बुक किया गया",
  bookedFor : "सौंप दिया",
  assignedTo: "को सौंपना",
  tId : "टास्कआईड",
  req_veh : "अनुरोधित वाहन",
  taskType : "कार्य प्रकार",
  ACTIVE : "सक्रिय",
  ASSIGNED : "सौंपा गया",
  CLOSED : "बंद है",
  PENDING : "लंबित",
  userprofile : "उपयोगकर्ता प्रोफ़ाइल",
  editprofile : "प्रोफ़ाइल संपादित करें",
  area : "क्षेत्र",
  attended_by : "भागीदार",
  time : "समय",
  acknowledgement : "स्वीकृति",
  segregation : "पृथक्करण",
  no_data_found : "इस तिथि के लिए कोई डेटा नहीं मिला",
  go_to_c : "कैलेंडर दिखाओ",
  confirm_to_exit : "बाहर निकलने की पुष्टि?",
  hold_on : "Hold on!",
  exit_app : "ऐप से बाहर निकलें",
  tag_added : "नया टैग सफलतापूर्वक जोड़ा गया!",
  garbage_collected : "कचरा एकत्रित",
  garbage_segregation : "कूड़ा सेग्रीगेशन नहीं किया गया",
  garbage_picker_absent : "कूड़ा बीनने वाला नदारद",
  unavailable:"",
  loading_com : "शिकायतें लोड हो रही हैं",
  loading_book : "बुकिंग लोड हो रही है",
  saving_complaint : "बचत शिकायत",
  keep_our_mun : "अपना जगदलपुर स्वच्छ रखें",
  your_feedback_submitted : "आपकी प्रतिक्रिया सफलतापूर्वक सबमिट की गई",
  
  //  your_house_holding : ""

} 