export default {
  notifications : "सूचनाएं",
  mapView : "नक्शा देखें",
  editDetail : "विवरण बदलें",
  complaint : "शिकायत",
  complaints : "शिकायतों",
  logout : "लॉग आउट",
  welcome : "स्वागत है",
  name : "नाम",
  phoneNumber : "फ़ोन नंबर",
  email : "ईमेल",
  address : "पता",
  select_your_ward : "अपने वार्ड का चयन करें",
  select_your_type : "अपने प्रकार का चयन करें",
  update_current_location: "वर्तमान स्थान अपडेट करें",
  submit: "भेजें",
  details : "विवरण",
  loading : "लोड हो रहा है",
  take_picture : "तस्वीरें ले",
  edit_picture : "चित्र बदलें",
  type_of_complaint : "शिकायत का प्रकार",
  message : "संदेश",
  send : "भेजें",
  send_otp : "OTP भेजें",
  confirm : "पुष्टि करें",
  complaint_message : "शिकायत संदेश",
  confirmation_code : "पुष्टि कोड",
  firstName_lastName : "हिमांशु राज",
  search : "ढूढें",
  sync_photo_locally: "फ़ोटो को स्थानीय रूप से सिंक करें",
  select_language : "भाषा का चयन करें",
  we_shall_contact_you_soon: "हम जल्द ही आपसे संपर्क करेंगे",
  please_enter_complaint_message : "कृपया शिकायत संदेश दर्ज करें",
  alert_c : 'संदेश',
  ok_c : "ठीक है",
  cancel : "बंद करे",
  save : "सहेजें",
  please_grant_location_permission: "कृपया स्थान अनुमति प्रदान करें",
  please_enter_10_digit_phonenumber : "कृपया 10 अंकों का वैध फोन दर्ज करें",
  please_enter_valid_info : "कृपया मान्य जानकारी दर्ज करें",
  please_enter_valid_phoneNumber : "कृपया एक वैध नंबर डालें",
  please_enter: "कृपया दर्ज करें - ",
  message_sent_successfully: "संदेश सफलतापूर्वक भेजा जा चुका है",
  your_notifications: "आपकी सूचनाएं",
  register_your_complaint: "अपनी शिकायत दर्ज करें",
  image_loading: "फोटो लोड हो रहा है",
  please_wait_until_image_is_loaded: "कृपया फ़ोटो लोड होने तक प्रतीक्षा करें",
  oops_there_is_an_error_while_getting_image_url: "उफ़ !! फ़ोटो प्राप्त करते समय कोई त्रुटि है",
  oops_there_is_an_error_whie_storing_image: "उफ़ !! फ़ोटो संग्रहीत करते समय कोई त्रुटि है",
  your_complaints_list : "आपकी शिकायतों की सूची",
  add_complaint : "नई शिकायत",
  your_complaints : "आपकी शिकायतें",
  about_us : "हमारे बारे में",
  landmark : "सीमा चिन्ह",
  near_shiv_temple: "शिव मंदिर के पास",
  close_c : "बंद करे",
  delete_c : "हटाएँ",
  otp_sent : "OTP भेजा गया",
  resend_otp : "ओटीपी पुनः भेजें",
  an_initiative_by : "द्वारा एक पहल",
  fetching_notification : "सूचना ला रहा है",
  deleting_notif: "सूचना हटाना",
  mayor_name : "श्रीमती रूबी देवी",
  comissioner_name : "श्री धीरेन्द्र पासवान",
  notif_welcome_msg : "कचरा इधर-उधर न फेंके। डस्टबिन का उपयोग करें। आपका शहर आपका अपना घर है। स्वच्छ शहर, स्वच्छ घर।",
  ward : "वार्ड",
  enter_mobile_number : "अपना मोबाइल नंबर दर्ज करें",
  we_have_sent_otp_on : "हमने ओटीपी भेजा है ",
  reeenter_number : "फिर से नंबर दर्ज करें",
  please_grant_location_permission : "कृपया स्थान की अनुमति प्रदान करें",
  see_nearby_garbage_vehicles : "पास में कचरा वाहन देखें",
  we_will_access_your_location : "हम आपके स्थान पर पहुँचेंगे",
  allow_c : "अनुमति",
  comissioner : "नगर आयुक्त",
  mayor : "नगर सभापति",
  otp: "ओ.टी.पी.",
  collector : "जिलाधीश",
  adm : "अतिरिक्त जिला दंडनायक",
  executive_officer : "नगर कार्यपालक अधिकारी",
  please_confirm : "कृपया पुष्टि करें",

  // types of garbage
  garbage_dump : "कूड़े का ढेर",
  garbage_vehicle_Not_arrived : "कचरा वाहन नहीं पहुंचा",
  dustbins_not_cleaned: "डस्टबिन की सफाई नहीं",
  sweeping_not_done: "सफाई नहीं हुई",
  dead_animal: "मृत पशु",
  public_toilets_cleaning: "सार्वजनिक शौचालय की सफाई",
  public_toilets_blockage: "सार्वजनिक शौचालय रुकावट",
  no_water_supply_in_public_toilets: "सार्वजनिक शौचालयों में पानी की आपूर्ति नहीं",
  no_electricity_in_public_toilets: "सार्वजनिक शौचालयों में बिजली नहीं",
  others: "अन्य",
  drain_not_cleaned : "नाली की सफाई नहीं हुई",

  tasks : "कार्य",
  your_tasks : "आपके कार्य",
  view_in_map : "मानचित्र में देखें",
  done : "किया हुआ",
  not_my_work : "मेरे काम का नहीं",
  close : "बंद करे",
  status : "स्थिति",
  creation_date : "निर्माण तिथि",
  task_type : "कार्य प्रकार",
  please_enter_your_comment : "कृपया अपनी टिप्पणी दर्ज करें",
  agent_is_not_approved : "सफाई मित्र प्रोफ़ाइल स्वीकृत नहीं है, कृपया व्यवस्थापक से संपर्क करें।",
  duty_is_off: "ड्यूटी बंद है !!!",
  yes_c : "हाँ",
  no_c : "नहीं",
  segregation : "अलगाव",
  this_is_an_agent_app : "यह एक एजेंट ऐप है",
  home : "होम",
  acknowledgement : "स्वीकृति",
  boardUsers : "बोर्ड उपयोगकर्ता",
  boardCheckpoints : "बोर्ड नाका",

  please_grant_location_permission_c : "कृपया ध्यान से देखें",
  error_in_getting_current_location: "वर्तमान स्थान प्राप्त करने में त्रुटि",
  error_in_getting_location_please_set_location_in_map : "स्थान पाने में त्रुटि। कृपया मानचित्र में स्थान सेट करें।",
  or_c : "या",
  select_location : "स्थान चुनें",
  select_location_from_map : "मानचित्र से स्थान का चयन करें",
  select_current_location : "वर्तमान स्थान का चयन करें",
  user_onboarded_successfully : "उपयोगकर्ता सफलतापूर्वक ऑनबोर्ड किया गया",
  user_with_same_number_exists : "समान संख्या वाला उपयोगकर्ता मौजूद है",
  location_request : "कृपया सुघर जगदलपुर को स्थान सेवाओं का उपयोग करने की अनुमति दें",
  userId : "यूज़र आईडी",
  editYourDetail : "अपना विवरण संपादित करें",
  images : "इमेजिस",
  currently_you_donot_have_any_assignments : "वर्तमान में आपके पास कोई असाइनमेंट नहीं है",
  currently_you_donot_have_any_notifications : "वर्तमान में आपके पास कोई सूचना नहीं है",
  currently_your_history_list_is_empty : "वर्तमान में आपकी इतिहास सूची खाली है",
  currently_you_donot_have_daily_images : "आपने आज कोई चित्र अपलोड नहीं किया है",
  history : "इतिहास",
  attendance : "उपस्थिति",
  duty_on_c : "कार्य पर",
  duty_off_c : "कार्य अंत",
  no_attendance_found_for_this_date :"इस तिथि के लिए कोई उपस्थिति नहीं मिली",
  see_route: "मार्ग देखें",
  assignments :"असाइनमेंट",
  view_more : "और देखें",
  state: "स्थि‍ति",
  raised_by : "उपयोगकर्ता",
  scan_qr : "क्यू आर कोड स्कैन करें",
  qr_code_scan : "क्यूआर कोड सफलतापूर्वक स्कैन किया गया!",
  one_or_more : "एक या अधिक फ़ोटो जोड़ें",
  updateCheckpoint : "अपडेट नाका",
  update_location : "अपडेट स्थान",
  preview_details : "पूर्वावलोकन विवरण",
  reset : "रीसेट",
  _onBoardResidents   : "ऑनबोर्डनिवासी",
  search_user_by_phoneNumber: "फ़ोन नंबर से खोजें",
  search_user_by_name : "नाम से उपयोगकर्ता खोजें",
  update_details : "विवरण अपडेट करें",
  updateCitizen: "नागरिक अपडेट करें",
  refresh : "ताज़ा करना",
  no_survey_assigned : "कोई सर्वेक्षण असाइन नहीं किया गया",
  get_user_details  : "द्वारा उपयोगकर्ता विवरण प्राप्त करें",
  survey : "सर्वेक्षण",
  ctpt:"सीटीपीटी",
  updateResident: "अद्यतन निवासी",
  updatePlace : "अपडेटप्लेस",
  payments : "भुगतान",
  complaints : "शिकायतें",
  bookings:"बुकिंग के",
  isWasteCollected:"कचरा एकत्र किया जाता है?",
  isWasteSeggregated : "कचरा अलग किया जाता है?",
  unable_to_find_users : "उपयोक्ता ढूँढने में असमर्थ",
  acknow_user : "उपयोगकर्ता को स्वीकार करें",
  unable_to_find_ctpt:"सीटीपीटी खोजने में असमर्थ",
  acknow_ctpt:"स्वीकार करें सी.टी.पी.टी",

  update : "अद्यतन",
  add_user : "उपयोगकर्ता जोड़ें",
  please_enter_mobileNumber_or_aadhar_Number : "कृपया मोबाइल या आधार संख्या दर्ज करें",
  checkpoint_onboarded_successfully:"चेकपॉइंट सफलतापूर्वक ऑनबोर्ड हो गया",
 //hn
  boardCommercial :"जहाज पर वाणिज्यिक",
  boardCtpt : "ऑनबोर्ड सीटीपीटी",
  updatectpt : "सीटीपीटी अपडेट करें",
  please_take_image : "कृपया छवि लें",
  commercial_onboarded_successfully : "वाणिज्यिक सफलतापूर्वक ऑनबोर्ड हो गया",
//
  click_below:"अपने क्षेत्र का चयन करने के लिए नीचे क्लिक करें",
  click_to_change : "स्थान बदलने के लिए मानचित्र पर क्लिक करें",
  click_to_select :"स्थान का चयन करने के लिए मानचित्र पर क्लिक करें",
  click_to_attach :"फोटो संलग्न करने के लिए क्लिक करें",
  search_user_qr:"Qr द्वारा उपयोगकर्ता खोजें",
  no_user_with_this_qr_exists:"इस Qr वाला कोई उपयोगकर्ता मौजूद नहीं है",
  user_with_same_qr_exists : "समान qr वाला उपयोक्ता मौजूद है",
  check_with_same_qr_exists : "समान qr वाला चेकपॉइंट मौजूद है",
  ctpt_with_same_qr_exists : "समान qr वाला सीटीपीटी मौजूद है",
  scanned_qr_for:"स्कैन क्यूआर के लिए ",
  qr_code_attached:"क्यूआर कोड सफलतापूर्वक अटैच किया गया",
  location_sucess:"स्थान सफलतापूर्वक अपडेट किया गया..",
  take_image : "छवि लो",
  retake_image : "रीटेक इमेज",
  click_below_t:"अपना चेकप्वाइंट चुनने के लिए नीचे क्लिक करें",
  is_waste:"isWasteSeggregated",
  is_waste_c: "isWasteCollected",
  switch_on_duty_c : "सफाई मित्र प्रोफ़ाइल स्वीकृत नहीं है, कृपया व्यवस्थापक से संपर्क करें और फिर अपनी ड्यूटी चालू करें",
  switch_on_duty : "कृपया अपना कर्तव्य चालू करें",
  close_m : "नक्शा बंद करें",
  
  update_qr:"क्यूआर अपडेट करें",
  scanned_val :"स्कैन किया गया मान",
  close_map :"नक्शा बंद करें",
  please_take_image_of_house : "घर का फोटो",
  household : "परिवारों",
  checkpoint : "चौकियों",
  donot_have_phoneNumber_press_here : "फोन नंबर नहीं है? यहां दबाएं।",
  work_in_progress : "कार्य प्रगति पर है",
  fetching_tasks: "कार्यों को लाना",
  not_belongs_to_ward : "यह उपयोगकर्ता आपके वार्ड का नहीं है..!",
  otp_sent_to : "आपके मोबाइल नंबर पर ओटीपी भेज दिया गया है",
  dear_user : "प्रिय उपयोगकर्ता",
  permission_request: "आपको गतिविधि पहचान, मोटे स्थान सेवा, बढ़िया स्थान सेवाओं और फ़ाइल प्रबंधक और कैमरा तक पहुँच प्रदान करने की आवश्यकता है",
  ack_data_stored: "पावती डेटा सफलतापूर्वक संग्रहीत",
  location_captured : "स्थान सफलतापूर्वक कब्जा कर लिया",
  location_updated : "स्थान सफलतापूर्वक अपडेट किया गया",
  duty_hours : "ड्यूटी के घंटे(HH:MM)",
  photos : "तस्वीरें",
  route : "रूट",
  garbage_c:"कचरा एकत्रित",
  garbage_nc:"कूड़ा नहीं उठाया गया",
  no_data_found : "इस तिथि के लिए कोई डेटा नहीं मिला",
  history_details : "इतिहास विवरण",
  go_to_history: "इतिहास में जाओ",
  userprofile : "उपयोगकर्ता प्रोफ़ाइल",
  editprofile : "प्रोफ़ाइल संपादित करें",
  commercial : "व्यावसायिक",
  updateCommercial : "वाणिज्यिक अद्यतन करें",
  waste:"कचरा",
  pending_amount : "बकाया राशि",
  advance_amount : "अग्रिम भुगतान",
  select_your_payment: "अपना भुगतान चुनें",
  paymenttype : "भुगतान प्रकार",
  payment_mode : "अपना भुगतान मोड चुनें",
  payment_added : "भुगतान सफलतापूर्वक जोड़ा गया",
  go_to_ack : "पावती पर जाएं",
  go_to_payment : "पेमेंट पर जाएं",
  add_payment : "भुगतान जोड़ें",
  places : "प्लेस",
  saathi_duty_is_off : "सफाई मित्र की ड्यूटी बंद है",
  auto_start_message: "सुघर जगदलपुर को ऑटो स्टार्ट परमिशन एक्सेस की अनुमति दें",
  prior_to_work :  "काम से पहले",
  complaint_type : "शिकायत प्रकार",
  upi : "यूपीआई:",
  cash : "नकद",
  sk_name : "दुकानदार का नाम",
  sh_name : "दुकान का नाम",
  filter_c: "फ़िल्टर",
  fuel_management : "ईंधन प्रबंधन",
  new_request : "नई विनती",
  click_below_v : "वाहन का चयन करने के लिए नीचे क्लिक करें",
  fuel_quantity : "ईंधन की मात्रा",
  en_fuel_quantity : "ईंधन मात्रा दर्ज करें",
  select_your_vehicle : "वाहन का चयन करें",
  add_request : "ईंधन अनुरोध",
  fuel_detail_added_successfully : "ईंधन विवरण सफलतापूर्वक जोड़ा गया",
  please_select_vehicle : "कृपया वाहन चुनें",
  vehicle_id : "वाहन आईडी",
  date : "तारीख",
  quantity : "मात्रा",
  saathi : "साथी",
  all : "सभी",
  online_saathi : "ऑनलाइन साथी",
  offline_saathi : "ऑफलाइन साथी",
  res_ack : "उपयोगकर्ता स्वीकार करते हैं",
  com_ack : "विज्ञापन स्वीकार करते हैं",
  res_onBoard : "बोर्ड पर उपयोगकर्ता",
  com_onBoard : "बोर्ड पर विज्ञापन",
  back : "पीछे",
history_t : "इतिहास का  ",
issupervisor : "पर्यवेक्षक है",
supervisor_name : "पर्यवेक्षक का नाम",
staff : "नियुक्त कर्मचारी",
type : "प्रकार",
please_enter_userid : "कृपया उपयोगकर्ता आईडी दर्ज करें",
registartion : "पंजीकरण",
view_staff : "कर्मचारी देखें",
reports : "रिपोर्टों",
saathi_attendance : "स्टाफ उपस्थिति",
staff_is_not_approved : "स्टाफ स्वीकृत नहीं है",
father_name : "पिता का नाम",
please_enter_name : "कृपया नाम दर्ज करें",
please_enter_number : "कृपया फ़ोन नंबर दर्ज करें",
please_enter_image : "कृपया फोटो पर क्लिक करें",
view : "देखना",
edit : "संपादन करना",
go_to_viewstaff : "व्यूस्टाफ पर जाएं",
please_take_image_properly : "कृपया छवि ठीक से लें",
data_updated : "डेटा अपडेट किया गया",
spot_fine :"ठीक है",
enter_comment : "टिप्पणी दर्ज करें",
comment : "टिप्पणी",
please_enter_father : "कृपया पिता का नाम दर्ज करें",
edit_staff : "कर्मचारी संपादित करें",
staff_details : "स्टाफ विवरण",
staff_reports : "स्टाफ रिपोर्ट",
no_staff_assign : "आपके लिए कोई स्टाफ नियुक्त नहीं है",
image : "फोटो",
post_spotfine : "स्पॉटफाइन पोस्ट करें",
please_upload_image : "कृपया छवि अपलोड करें",
please_select_area : "कृपया क्षेत्र चुनें",
please_enter_comment : "कृपया टिप्पणी दर्ज करें",
please_enter_fathefr_name: "कृपया पिता का नाम दर्ज करें",
store_image_of_staff: "स्टाफ की छवियाँ संग्रहीत करें",
all_images_stored : "सभी स्टाफ की संग्रहीत छवियाँ",
not_available : "उपलब्ध नहीं है",
current_status : "वर्तमान स्थिति",
attendance : "उपस्थिति",
please_take_image_of_saathi : "कृपया साथी की छवि लें",
please_select_staff : "कृपया स्टाफ का चयन करें",
enter_your_text : "अपना टेक्स्ट यहां दर्ज करें..",
saathi_exist : "एक ही फोन नंबर वाले कर्मचारी पहले से मौजूद हैं",
onboard_staff : "जहाज पर कर्मचारी",
update_staff : "स्टाफ़ अपडेट करें",
select_saathi : "स्टाफ का चयन करें",
in_time_s : "इन टाइम सेल्फी",
out_time_s : "आउट टाइम सेल्फी",
please_enter_valid_otp : "कृपया वैध ओटीपी दर्ज करें",
press_button : "ऐप को अपडेट करने के लिए बटन दबाएं:",
update_app : "ऐप अपडेट करें",
error_while_capturing_image : "उफ़!! छवि कैप्चर करते समय कोई त्रुटि हुई",
app_version : "एप्लिकेशन वेरीज़न :",
attendance_type : "उपस्थिति प्रकार",
please_select_type : "कृपया उपस्थिति प्रकार चुनें",
image_added_sucessfully : "छवि सफलतापूर्वक जोड़ी गई",
supervisor : "Supervisor",
failed_to_mark_attendance : "उपस्थिति दर्ज करने में विफल",
self_attendace_marked : "पर्यवेक्षक के लिए चेहरे से उपस्थिति की आवश्यकता नहीं है!!!",
matching_face : "Matching Face !!!",
no_face_matched : "कोई चेहरा मेल नहीं खाता",
no_saathi_data_fetched : 'कोई साथी डेटा नहीं लाया गया!!!',
failed_to_recognize_face : "चेहरा पहचानने में विफल",
manual_attendance : "मैनुअल उपस्थिति",
failed_to_capture_image : "छवि कैप्चर करने में विफल",
no_face_found : "कोई चेहरा नहीं मिला",
please_blink_your_eyes : "कृपया अपनी आँखें झपकाएँ",
please_come_closer_to_camera : "कृपया कैमरे के करीब आएं",
please_take_intime_selfie : "कृपया समय पर उपस्थिति दर्ज कराएं",
intime_selfie_already_taken_for_this_saathi : "इस स्टाफ की इनटाइम अटेंडेंस पहले ही ली जा चुकी है",
failed_to_get_saathiList : "साथी सूची प्राप्त करने में विफल",
failed_to_store_data : "डेटा संग्रहीत करने में विफल",
intime_attendance_already_taken_through_face_attendance : "फेस अटेंडेंस के माध्यम से समय पर उपस्थिति पहले ही ली जा चुकी है।",
intime_attendance_already_taken_through_manual_attendance : "मैन्युअल उपस्थिति के माध्यम से समय पर उपस्थिति पहले ही ली जा चुकी है।",
please_take_intime_attendance : "कृपया इनटाइम उपस्थिति लें।",
outtime_attendance_already_taken_through_face_attendance : "आउटटाइम उपस्थिति पहले से ही चेहरे की उपस्थिति के माध्यम से ली गई है।",
outtime_attendance_already_taken_through_manual_attendance : "आउटटाइम उपस्थिति पहले ही मैन्युअल उपस्थिति के माध्यम से ली जा चुकी है।",
saving_attendance : "उपस्थिति सहेजा जा रहा है",
getting_address_of_current_location : "आपके स्थान का पता प्राप्त करना",
saving_data : "डेटा सहेजा जा रहा है",
getting_staff : "स्टाफ प्राप्त करना",
click_on_get_staff_to_getData : "स्टाफडेट प्राप्त करने के लिए रिफ्रेश पर क्लिक करें",
assigned_spotfine : "स्पॉटफाइन सौंपा गया",
assigned_tasks : "नियुक्त किए गया कार्य",
fetching_tasks : "स्पॉटफ़ाइन लाया जा रहा है",
no_wards_assigned : "आपको कोई क्षेत्र नहीं सौंपा गया है",
please_switch_location : "Please switch on your location in mobile",
switch_on_location : "अपना स्थान चालू करें",
getting_users : "घर-गृहस्थी और विज्ञापन प्राप्त करना"
}