export default {
    notifications : "ବିଜ୍ଞପ୍ତି",
    mapView : "ମାନଚିତ୍ରରେ ଦେଖନ୍ତୁ",
    editDetail : "ବିବରଣୀ ପରିବର୍ତ୍ତନ",
    complaint : "ଅଭିଯୋଗ",
    logout : "ପ୍ରସ୍ଥାନ",
    welcome : "ସ୍ୱାଗତ",
    name : "ନାମ",
    phoneNumber : "ଫୋନ୍ ନମ୍ବର",
    email : "ଇ-ମେଲ୍",
    address : "ଠିକଣା",
    select_your_ward : "ଆପଣଙ୍କର ୱାର୍ଡ ଚୟନ",
    update_current_location: "ମାନଚିତ୍ରରେ ପରିବର୍ତ୍ତନ କରନ୍ତୁ",
    submit: "ଦାଖଲ କରନ୍ତୁ",
    details : "ବିବରଣୀ",
    loading : "ଅପେକ୍ଷା କରନ୍ତୁ ...",
    take_picture : "ଫଟୋ ନିଅନ୍ତୁ",
    edit_picture : "ଫଟୋ ପରିବର୍ତ୍ତନ",
    type_of_complaint : "ଅଭିଯୋଗର ପ୍ରକାରଗୁଡିକ",
    message : "ବାର୍ତ୍ତା",
    send : "ପଠାନ୍ତୁ",
    send_otp : "OTP ପଠାନ୍ତୁ",
    confirm : "ନିଶ୍ଚିତ କର",
    complaint_message : "ଅଭିଯୋଗ ବାର୍ତ୍ତା",
    confirmation_code : "ନିଶ୍ଚିତକରଣ ସଂଖ୍ୟା",
    firstName_lastName : "ପ୍ରଥମ-ନାମ ଉପନାମ",
    search : "ସନ୍ଧାନ",
    select_language : "ଭାଷା ଚୟନ",
    we_shall_contact_you_soon: "ଆମେ ଶୀଘ୍ର ଆପଣଙ୍କ ସହିତ ଯୋଗାଯୋଗ କରିବୁ",
    please_enter_complaint_message : "ଦୟାକରି ଅଭିଯୋଗ ବାର୍ତ୍ତା ଦିଅନ୍ତୁ",
    alert_c : "ସତର୍କ",
    ok_c : "ଠିକ୍ ଅଛି",
    cancel : "ବାତିଲ୍ କରନ୍ତୁ",
    save : "ସଂରକ୍ଷଣ କରନ୍ତୁ",
    please_grant_location_permission: "ଦୟାକରି ଅବସ୍ଥାନ ଅନୁମତି ଦିଅନ୍ତୁ",
    please_enter_10_digit_phonenumber : "ଦୟାକରି ୧୦ ଅଙ୍କ ବିଶିଷ୍ଟ ଫୋନ୍ ନମ୍ବର ଦିଅନ୍ତୁ",
    please_enter_valid_info : "ଦୟାକରି ସଠିକ ସୂଚନା ଦିଅନ୍ତୁ",
    please_enter_valid_phoneNumber : "ଦୟାକରି ସଠିକ ଫୋନ୍ ନମ୍ବର ଦିଅନ୍ତୁ",
    please_enter: "ଦୟାକରି ଲେଖନ୍ତୁ :",
    message_sent_successfully: "ବାର୍ତ୍ତା ସଫଳତାର ସହିତ ପଠାଗଲା",
    your_notifications: "ଆପଣଙ୍କର ବିଜ୍ଞପ୍ତି ଗୁଡିକ",
    register_your_complaint: "ଅଭିଯୋଗ ପଞ୍ଜିକରଣ",
    image_loading: "ଫଟୋ ସଂଗ୍ରହ",
    please_wait_until_image_is_loaded: "ଫଟୋ ସଂଗ୍ରହ ହେବା ପର୍ଯ୍ୟନ୍ତ ଦୟାକରି ଅପେକ୍ଷା କରନ୍ତୁ",
    oops_there_is_an_error_while_getting_image_url: "ଫଟୋ ଲିଙ୍କ୍ ପାଇବାବେଳେ ଏକ ତ୍ରୁଟି ଅଛି",
    oops_there_is_an_error_whie_storing_image: "ଫଟୋ ସଂରକ୍ଷଣ କରିବା ସମୟରେ ଏକ ତ୍ରୁଟି ଅଛି",
    your_complaints_list : "ଆପଣଙ୍କର ଅଭିଯୋଗ ତାଲିକା ",
    add_complaint : "ନୂତନ ଅଭିଯୋଗ ସୃଷ୍ଟି ",
    your_complaints : "ଆପଣଙ୍କର ଅଭିଯୋଗ ଗୁଡ଼ିକ",
    about_us : "ଆମ ବିଷୟରେ",
    landmark : "ନିକଟସ୍ତ ପରିଚିତ ସ୍ଥାନ", 
    near_shiv_temple: "ଶିବ ମନ୍ଦିର ନିକଟରେ",
    close_c : "ବନ୍ଦ",
    delete_c : "ଡିଲିଟ୍",
    otp_sent : "OTP ପଠାଯାଇଛି",
    resend_otp : "ପୁଣି OTP ପଠାଯାଇଛି",
    an_initiative_by : "ଏ ପଦକ୍ଷେପ ଆରମ୍ଭ କରାଯାଇଛି",
    deleting_notif : "ଡିଲିଟ୍ ବିଜ୍ଞପ୍ତି",
    fetching_notification : "ବିଜ୍ଞପ୍ତି ସଂଗ୍ରହ",
    enter_mobile_number : "ମୋବାଇଲ୍ ନଂ ଦିଅନ୍ତୁ",
    we_have_sent_otp_on : "ଆମେ OTP ପଠାଇଛୁ",
    reenter_number : "ପୁଣି ମୋବାଇଲ୍ ନମ୍ବର ଦିଅନ୍ତୁ",
    see_nearby_garbage_vehicles : "ନିକଟସ୍ଥ ଅଳିଆ ଗାଡି ଦେଖନ୍ତୁ",
    we_will_access_your_location : "ଆମେ ଆପଣଙ୍କ ଅବସ୍ଥାନକୁ ବ୍ୟବହାର କରୁଛୁ",
    allow_c : "ଅନୁମତି ଦିଅନ୍ତୁ",
    ward : "ୱାର୍ଡ",
    collector : "ଜିଲ୍ଲାପାଳ",
    adm : "ମାଜିଷ୍ଟ୍ରେଟେ",
    otp : "OTP",
    executive_officer : "",

    // types of garbage
    garbage_dump : "ଅଳିଆ ଆବର୍ଜନା ଉଠାଯାଇ ନାହିଁ",
    garbage_vehicle_Not_arrived : "ଅଳିଆ ଗାଡି ଆସିନାହିଁ ",
    dustbins_not_cleaned: "କୁଡାଦନା ସଫା ହୋଇନାହିଁ",
    sweeping_not_done: "ରାସ୍ତା ସଫା ହୋଇନାହିଁ",
    dead_animal: "ମୃତ ଜୀବଜନ୍ତୁ",
    public_toilets_cleaning: "ସର୍ବସାଧାରଣ ଶୌଚାଳୟ ସଫା",
    public_toilets_blockage: "ସର୍ବସାଧାରଣ ଶୌଚାଳୟ ଅବରୋଧ",
    no_water_supply_in_public_toilets: "ସର୍ବସାଧାରଣ ଶୌଚାଳୟରେ ଜଳ ଯୋଗାଣ ନାହିଁ",
    no_electricity_in_public_toilets: "ସର୍ବସାଧାରଣ ଶୌଚାଳୟରେ ବିଦ୍ୟୁତ୍ ନାହିଁ",
    others: "ଅନ୍ୟ ବିଷୟ",
    drain_not_cleaned : "ନାଳ ସଫା ହୋଇନାହିଁ",
    Acknowledgements: "ନିଶ୍ଚୟ କରିବା",
    agent_is_not_approved: "ସାଥୀ ପ୍ରୋଫାଇଲ୍ ଅନୁମୋଦିତ ନୁହେଁ, ଦୟାକରି ଆଡମିନ ସହିତ ଯୋଗାଯୋଗ କରନ୍ତୁ ।",
    allow: "ଅନୁମତି",
    assignments: "କାର୍ଯ୍ୟଗୁଡିକ",
    auto_start_message: "ଅଟୋ ଆରମ୍ଭ କରିବାକୁ ଦୟାକରି ବିନିମାଇଜକୁ ଅନୁମତି ଦିଅନ୍ତୁ ",
    auto_start_permission: "ଅଟୋ ଆରମ୍ଭ ଅନୁମତି ",
    boardUsers: "ଅନବୋର୍ଡ ବାସିନ୍ଦା ।",
    close: "ବନ୍ଦ",
    creation_date: "ସୃଷ୍ଟି ତାରିଖ",
    currently_you_donot_have_any_assignments: "ବର୍ତ୍ତମାନ ଆପଣଙ୍କୁ କୌଣସି କାର୍ଯ୍ୟ ଦିଆଯାଇନାହିଁ ।",
    currently_your_history_list_is_empty: "ବର୍ତ୍ତମାନ ଆପଣଙ୍କର ବିବରଣୀ ତାଲିକା ଖାଲି ଅଛି ।",
    done: "ସମାପ୍ତ",
    duty_is_off: "କର୍ତ୍ତବ୍ୟ ଶେଷ ଅଛି !!! ",
    duty_off_c: "କର୍ତ୍ତବ୍ୟ ଶେଷ ",
    duty_on_c: "କର୍ତ୍ତବ୍ୟ ଆରମ୍ଭ ",
    error_in_getting_current_location: "ସାମ୍ପ୍ରତିକ ଅବସ୍ଥାନ ମିଳୁ ନାହିଁ ।",
    error_in_getting_location_please_set_location_in_map: "ଅବସ୍ଥାନ ପାଇବାରେ ତ୍ରୁଟି | ଦୟାକରି ମାନଚିତ୍ରରେ ସ୍ଥାନ ବାଛନ୍ତୁ । ",
    failed_to_get_location: "ଅବସ୍ଥାନ ପାଇବାରେ ବିଫଳ । ",
    history: "ବିବରଣୀ",
    home: "ମୂଳପୃଷ୍ଠା",
    no_c: "ନା ",
    not_my_work: "ମୋର କାମ ନୁହେଁ ।",
    notif_welcome_msg: "ଚାରିଆଡେ ଅଳିଆ ପକାନ୍ତୁ ନାହିଁ । ଡଷ୍ଟବିନ ବ୍ୟବହାର କରନ୍ତୁ । ଆମ ସହର ଆମ ଘର । ପରିଷ୍କାର ସହର, ପରିଷ୍କାର ଘର। ",
    or_c: "କିମ୍ବା ",
    permission_request: "ଅତିରିକ୍ତ କାର୍ଯ୍ୟକଳାପ ଚିହ୍ନଟ, କଠିନ ଅବସ୍ଥାନ ସେବା, ଉତ୍ତମ ଅବସ୍ଥାନ ସେବା, ଫାଇଲ ପରିଚାଳକ ଏବଂ କ୍ୟାମେରା ପରିଚାଳନା କରିବାକୁ ଦୟାକରି ବିନିମାଇଜ୍ କୁ ଅନୁମତି ଦିଅନ୍ତୁ । ",
    please_confirm: "ଦୟାକରି ନିଶ୍ଚିତ କରନ୍ତୁ । ",
    please_enter_your_comment: "ଦୟାକରି ଆପଣଙ୍କର ମନ୍ତବ୍ୟ ଦିଅନ୍ତୁ । ",
    please_grant_location_permission_c: "ଦୟାକରି ଅବସ୍ଥାନ ଅନୁମତି ଦିଅନ୍ତୁ । ",
    please_select_a_location: "ଦୟାକରି ଏକ ଅବସ୍ଥାନ ବାଛନ୍ତୁ । ",
    reeenter_number: "ପୁଣି ନମ୍ବର  ଦିଅନ୍ତୁ  ",
    refresh: "ରିଫ୍ରେଶ",
    saathi_duty_is_off: "ସାଥୀର ଡ୍ୟୁଟି ବନ୍ଦ ଅଛି",
    scan_qr: "Qr ସ୍କାନ୍ ",
    segregation: "ଅଲଗା ଅଲଗା ",
    select_current_location: "ସାମ୍ପ୍ରତିକ ଅବସ୍ଥାନ ଚୟନ ",
    select_location: "ଅବସ୍ଥାନ ଚୟନ ",
    select_location_from_map: "ମାନଚିତ୍ରରୁ ସ୍ଥାନ ଚୟନ କରନ୍ତୁ । ",
    status: "ସ୍ଥିତି ",
    survey: "ସର୍ବେକ୍ଷଣ ",
    task_type: "କାର୍ଯ୍ୟ ପ୍ରକାର ",
    tasks: "କାର୍ଯ୍ୟଗୁଡିକ ",
    this_is_an_agent_app: "ଏହା ଏକ ଏଜେଣ୍ଟ ଆପ୍ । ",
    unable_to_find_users: "ଉପଭୋକ୍ତାଙ୍କୁ ଖୋଜିବାରେ ଅସମର୍ଥ । ",
    userId: "ଉପଭୋକ୍ତାଙ୍କ ନମ୍ବର  ",
    user_onboarded_successfully: "ଉପଭୋକ୍ତା ସଫଳତାର ସହିତ ଅନବୋର୍ଡ  କରାଗଲା।",
    user_with_same_number_exists: "ଉପଭୋକ୍ତାଙ୍କ ନମ୍ବର ଆଗରୁ ଉପଲବ୍ଧ ଅଛି ।",
    view_in_map: "ମାନଚିତ୍ରରେ ଦେଖନ୍ତୁ ।",
    work_in_progress:  "କାମ ଚାଲୁଅଛି ",
    yes_c: "ହଁ",
    acknowledgement: "ସ୍ୱୀକୃତି",
    image_loaded_successfully: "ଛବି ଲୋଡ୍ ସଫଳ",
    images: "ଛବି",
    currently_you_donot_have_any_notifications: "ବର୍ତ୍ତମାନ ଆପଣଙ୍କର କିଛି ବିଜ୍ଞପ୍ତି ନାହିଁ",
    noOfPersons: "ଲୋକ ସଂଖ୍ୟା",
    present:"ଉପସ୍ଥିତ",
    absent: "ଅନୁପସ୍ଥିତ",
    no_user_with_this_number_exists : "ଏହି ନମ୍ବରରେ କୌ ଣସି ଉପଭୋକ୍ତା ନାହାଁନ୍ତି",
    failed_to_update_citizen : "ନାଗରିକ ଅଦ୍ୟତନ କରିବାରେ ବିଫଳ",
    user_detail_updated_successfully : "ଉପଭୋକ୍ତା ବିବରଣୀ ସଫଳତାର ସହିତ ଅଦ୍ୟତନ ହେଲା",
    donot_have_phoneNumber_press_here : "ଫୋନ୍ ନମ୍ବର ? ଏଠାରେ ଦିଅନ୍ତୁ",
    please_enter_name : "ଦୟାକରି ନାମ ପ୍ରବେଶ",
    no_user_with_this_name_exists : "ଏହି ନାମରେ କୌ ଣସି ଉପଭୋକ୍ତା ନାହାଁନ୍ତି",
    search_user_by_name : "ନାମ ଅନୁଯାୟୀ ଉପଭୋକ୍ତା ସନ୍ଧାନ",
    please_take_image : "ଦୟାକରି ଫୋଟ  ନିଅନ୍ତୁ",
    drainImage : "ନାଳର ଫୋଟ ",
    toiletStatus : "ଶୌଚାଳୟ",
    absent : "ନାହିଁ",
    twinPit : "ନନ୍ଦ ଟାଙ୍କି",
    septicTank : "ସେପ୍ଟିକ୍ ଟ୍ୟାଙ୍କ",
    drain : "ନାଳ",
    both :  "ଉଭୟ",
    deSludgingDate : "ଶେଷ ସଫା କରାଯାଇଥିଲା ",
    Dustbin_status : "ଡଷ୍ଟବିନ ",
    green : "ସବୁଜ ",
    blue : "ନୀଳ",
    water_supply : "ଜଳ ଯୋଗାଣ",
    safaAppInstalled : "ସଫା ଆପ୍",
    fiveMeterAwareness : "ପାଞ୍ଚ ମିଟର ସଚେତନତା",
    unknown :  "ଜଣା ନାହିଁ",
    household_person_count : "ଘରର ଲୋକ ସଂଖ୍ୟା ",
    houseType : "ଘରର ପ୍ରକାର",
    kachcha : "କଚ୍ଚା",
    pakka : "ପକ୍କା",
    house : "ଘର",
    own : "ନିଜ",
    Rent : "ଭଡା",
    yes : "ହଁ",
    no : "ନା",
    houseOwner : "ଘର",
    signup_to_continue: "ଜାରି ରଖିବାକୁ ସାଇନ୍ ଅପ୍",
    updateCitizen: "ନାଗରିକ ଅଦ୍ୟତନ",
    search_user_by_phoneNumber: "ଫୋନନମ୍ବର ଦ୍ୱାରା ସନ୍ଧାନ",
    update_details: "ବିବରଣୀ ଅଦ୍ୟତନ",
    typeOfToilet : "ଶୌଚାଳୟର ପ୍ରକାର",
    dustBinStatus : "ଡଷ୍ଟବିନ ",
    waterSupply : "ଜଳ ଯୋଗାଣ",
    dustBinColor : "ଡଷ୍ଟବିନ୍ ରଙ୍ଗ",
    supplyType : "ଯୋଗାଣ ପ୍ରକାର",
    holdingNo : "ହୋଲ୍ଡିଂ ନଂ",
    own : "ନିଜ",
    phd : "Phd",
    aadharNumber : "ଆଧାର ସଂଖ୍ୟା",
    please_enter_15_digit_aadharNumber : "ଦୟାକରି 12 ଅଙ୍କ ବିଶିଷ୍ଟ ଆଧାର ନମ୍ବର ପ୍ରବେଶ କରନ୍ତୁ",
    first_floor: "ପ୍ରଥମ ମହଲା",
    second_floor: "ଦୁଇ ମହଲା",
    third_floor: "ତିନି ମହଲା",
    tin: "ଟିଣ ଘର",
    please_take_image_of_house : "ଘରର ଫୋଟ",
    update : "ଅଦ୍ୟତନ",
    payments : "ଦେୟ",
    add_user : "ଉପଯୋଗକର୍ତ୍ତା ଯୋଡନ୍ତୁ |",
    would_you_like_to_continue : "ଆପଣ ଜାରି ରଖିବାକୁ ଚାହୁଁଛନ୍ତି କି?",
    payment : "ଦେୟ",
    switch_on_duty : "ଦୟାକରି ତୁମର କର୍ତ୍ତବ୍ୟ ଅନ୍ କର  |",
}