export default {
    notifications : "ବିଜ୍ଞପ୍ତି",
    mapView : "ମାନଚିତ୍ରରେ ଦେଖନ୍ତୁ",
    editDetail : "ବିବରଣୀ ପରିବର୍ତ୍ତନ",
    complaint : "ଅଭିଯୋଗ",
    logout : "ପ୍ରସ୍ଥାନ",
    welcome : "ସ୍ୱାଗତ",
    name : "ନାମ",
    phoneNumber : "ଫୋନ୍ ନମ୍ବର",
    email : "ଇ-ମେଲ୍",
    address : "ଠିକଣା",
    select_your_ward : "ଆପଣଙ୍କର ୱାର୍ଡ ଚୟନ",
    update_current_location: "ମାନଚିତ୍ରରେ ପରିବର୍ତ୍ତନ କରନ୍ତୁ",
    submit: "ଦାଖଲ କରନ୍ତୁ",
    details : "ବିବରଣୀ",
    loading : "ଅପେକ୍ଷା କରନ୍ତୁ ...",
    take_picture : "ଫଟୋ ନିଅନ୍ତୁ",
    edit_picture : "ଫଟୋ ପରିବର୍ତ୍ତନ",
    type_of_complaint : "ଅଭିଯୋଗର ପ୍ରକାରଗୁଡିକ",
    message : "ବାର୍ତ୍ତା",
    send : "ପଠାନ୍ତୁ",
    send_otp : "OTP ପଠାନ୍ତୁ",
    confirm : "ନିଶ୍ଚିତ କର",
    complaint_message : "ଅଭିଯୋଗ ବାର୍ତ୍ତା",
    confirmation_code : "ନିଶ୍ଚିତକରଣ ସଂଖ୍ୟା",
    firstName_lastName : "ପ୍ରଥମ-ନାମ ଉପନାମ",
    search : "ସନ୍ଧାନ",
    select_language : "ଭାଷା ଚୟନ",
    we_shall_contact_you_soon: "ଆମେ ଶୀଘ୍ର ଆପଣଙ୍କ ସହିତ ଯୋଗାଯୋଗ କରିବୁ",
    please_enter_complaint_message : "ଦୟାକରି ଅଭିଯୋଗ ବାର୍ତ୍ତା ଦିଅନ୍ତୁ",
    alert_c : "ସତର୍କ",
    ok_c : "ଠିକ୍ ଅଛି",
    cancel : "ବାତିଲ୍ କରନ୍ତୁ",
    save : "ସଂରକ୍ଷଣ କରନ୍ତୁ",
    please_grant_location_permission: "ଦୟାକରି ଅବସ୍ଥାନ ଅନୁମତି ଦିଅନ୍ତୁ",
    please_enter_10_digit_phonenumber : "ଦୟାକରି ୧୦ ଅଙ୍କ ବିଶିଷ୍ଟ ଫୋନ୍ ନମ୍ବର ଦିଅନ୍ତୁ",
    please_enter_valid_info : "ଦୟାକରି ସଠିକ ସୂଚନା ଦିଅନ୍ତୁ",
    please_enter_valid_phoneNumber : "ଦୟାକରି ସଠିକ ଫୋନ୍ ନମ୍ବର ଦିଅନ୍ତୁ",
    please_enter: "ଦୟାକରି ଲେଖନ୍ତୁ :",
    message_sent_successfully: "ବାର୍ତ୍ତା ସଫଳତାର ସହିତ ପଠାଗଲା",
    your_notifications: "ଆପଣଙ୍କର ବିଜ୍ଞପ୍ତି ଗୁଡିକ",
    register_your_complaint: "ଅଭିଯୋଗ ପଞ୍ଜିକରଣ",
    image_loading: "ଫଟୋ ସଂଗ୍ରହ",
    please_wait_until_image_is_loaded: "ଫଟୋ ସଂଗ୍ରହ ହେବା ପର୍ଯ୍ୟନ୍ତ ଦୟାକରି ଅପେକ୍ଷା କରନ୍ତୁ",
    oops_there_is_an_error_while_getting_image_url: "ଫଟୋ ଲିଙ୍କ୍ ପାଇବାବେଳେ ଏକ ତ୍ରୁଟି ଅଛି",
    oops_there_is_an_error_whie_storing_image: "ଫଟୋ ସଂରକ୍ଷଣ କରିବା ସମୟରେ ଏକ ତ୍ରୁଟି ଅଛି",
    your_complaints_list : "ଆପଣଙ୍କର ଅଭିଯୋଗ ତାଲିକା ",
    add_complaint: "ଶିକାୟତ ଯୋଗାଣି",
    your_complaints: "ଆପଣଙ୍କ ଶିକାୟତ",
    about_us: "ଆମର ବିଷୟରେ",
    landmark: "ଲ୍ୟାଣ୍ଡମାର୍କ",
    near_shiv_temple: "ଶିବ ମନ୍ଦିର ନିକଟରେ",
    close_c: "ବନ୍ଦ କରନ୍ତୁ",
    delete_c: "ମିଟାନ୍ତୁ",
    otp_sent: "OTP ପଠାନ୍ତୁ",
    resend_otp: "OTP ପୁଣି ପଠାନ୍ତୁ",
    an_initiative_by: "ଏକ ଉଦ୍ୟମ",
    deleting_notif: "ବିଜ୍ଞପ୍ତି ମିଟାନ୍ତୁ",
    fetching_notification: "ବିଜ୍ଞପ୍ତି ପାଇଁ ଗ୍ରହଣ କରାଯାଇଛି",
    notif_welcome_msg: "ବିଜ୍ଞପ୍ତି: କଚରା ସାରିବା ଓ କୁଣ୍ଡଳ ବ୍ୟବହାର କରନ୍ତୁ। ଆମେର ସହର ଆମର ଘର। ସ୍ୱଚ୍ଛ ସହର, ସ୍ୱଚ୍ଛ ଘର।",
    enter_mobile_number: "ଆପଣଙ୍କ ମୋବାଇଲ ନମ୍ବର ଦିଅନ୍ତୁ",
    we_have_sent_otp_on: "ଆମେ OTP ପଠାଇଛୁ",
    reeenter_number: "ନମ୍ବର ପୁଣି ଦିଅନ୍ତୁ",
    see_nearby_garbage_vehicles: "ନଜିକରେ ଆସୁନିବା କଚରା ଗାଡି ଦେଖନ୍ତୁ",
    we_will_access_your_location: "ଆମେ ଆପଣଙ୍କ ସ୍ଥାନ ଅଭିଗମନ କରିବୁ",
    allow_c: "ଅନୁମୋଦନ ଦିଅନ୍ତୁ",
    ward: "ପ୍ରତିଷ୍ଠାନ",
    comissioner: "ମୁନିସିପାଲ ଆଯାଳା",
    mayor: "ଚେୟରପର୍ସନ",
    otp: "OTP",
    collector: "ଜିଲ୍ଲା କଲେକ୍ଟର",
    adm: "ଅତିରିକ୍ତ ଜିଲ୍ଲା ମଗିସ୍ଟ୍ରେଟ",
    executive_officer: "କାର୍ଯ୍ୟକାରୀ ଅଫିସର",
    please_confirm: "ଦୟାକରି ନିଶ୍ଚିତ କରନ୍ତୁ",
    for_any_query_call_on_this_number: "ଯେଉଁ ପ୍ରଶ୍ନ ଥାଏ, ସେତେବେଳେ ଏହା ନମ୍ବର୍ ଫୋନ କରନ୍ତୁ",
    call: "ଫୋନ",
    sub_collector: "ସହ କଲେକ୍ଟର",
    no_active_complaints: "କୋଈ କାମିଲେ ଶିକାୟତ ନାହିଁ!!!",
    no_complaints_message: "ଆପଣ କୋନଠି କ୍ଷେତ୍ରରେ କୋଈ କାମିଲେ ଶିକାୟତ ପର୍ଯ୍ୟନ୍ତ ଫାଇଲ୍‌ ନାହିଁ।",
    places: "ସ୍ଥାନ",
    register_your_complaint: "ଆପଣଙ୍କ ଶିକାୟତ ଦାଖଲ କରନ୍ତୁ",
    mapViewFilters: "ମ୍ୟାପ୍ ଭ୍ୟୁ ଫିଲ୍ଟର୍‌ଗୁଡ଼ିକ",
    vehicles: "ଯାନ",
    park: "ପାର୍କ୍",
    hospital: "ଅସ୍ପତାଳ",
    dumping_point: "ଡମ୍ପିଂ ପଏଣ୍ଟ",
    toilet: "ଶୌଚାଳୟ",
    signup_to_continue: "ପ୍ରାରମ୍ଭ କରିବା ପାଇଁ ସାଇନ୍‌ ଅପ୍ କରନ୍ତୁ!!!",
    editYourDetail: "ଆପଣଙ୍କ ବିବରଣୀ ସମ୍ପାଦିତ କରନ୍ତୁ",
    places_around_you: "ଆପଣଙ୍କ ପାରମ୍ପରିକରେ ସ୍ଥାନ",
    no_places_yet: "କୌଣସି ସ୍ଥାନ ପାଇଁ ନାହିଁ।",
    no_places_message: "ଆପଣଙ୍କ କ୍ଷେତ୍ରରେ କୌଣସି ସ୍ଥାନ ପାଇଁ ନାହିଁ",
    placesFilter: "ଥାନରେ ସ୍ଥାନ",
    filter_c: "ଫିଲ୍ଟର",
    save_c: "ଦାଖଲ କରନ୍ତୁ",
please_enter_complaint_typesOfcomplaint: "ଦୟାକରି ଶିକାୟତ ଧରଣ ଚୟନ କରନ୍ତୁ",
view_more: "ଅଧିକ ଦେଖନ୍ତୁ",
complaint_id: "ଶିକାୟତ ଆଇଡି",
image: "ଛବି",
message: "ସଂଦେଶ",
garbage_dump: "କଚରା ଡମ୍ପ୍",
garbage_vehicle_Not_arrived: "କଚରା ଗାଡି ଆସିନାହିଁ",
dustbins_not_cleaned: "ଡଷ୍ଟବିନ୍‌ଗୁଡ଼ିକ ସଫାଇ ନାହିଁ",
sweeping_not_done: "ସ୍ୱିପିଂ ନହୁଏ",
dead_animal: "ମୃତ ପଶୁ",
public_toilets_cleaning: "ସର୍ବସାଧାରଣ ଶୌଚାଳୟ ସଫାଇ",
public_toilets_blockage: "ସର୍ବସାଧାରଣ ଶୌଚାଳୟ ଅଟକ",
no_water_supply_in_public_toilets: "ସର୍ବସାଧାରଣ ଶୌଚାଳୟରେ ପାଣି ସର୍ପିଷ୍ଟ ନାହିଁ",
no_electricity_in_public_toilets: "ସର୍ବସାଧାରଣ ଶୌଚାଳୟରେ ବିଦ୍ୟୁତ ସର୍ପିଷ୍ଟ ନାହିଁ",
others: "ଅନ୍ୟ",
drain_not_cleaned: "ଡ୍ରେନ୍‌ ସଫାଇ ନାହିଁ",
please_grant_location_permission_c: "ଦୟାକରି ସ୍ଥାନ ଅନୁମୋଦନ ଦିଅନ୍ତୁ",
error_in_getting_current_location: "ସ୍ଥାନ ପାଇଁ ଭୁଲ",
error_in_getting_location_please_set_location_in_map: "ସ୍ଥାନ ପାଇଁ ଭୁଲ। ଦୟାକରି ନକ୍ଶାରେ ସ୍ଥାନ ସେଟ୍ କରନ୍ତୁ।",
or_c: "ଅଥବା",
select_location: "ଲୋକେସନ ଚୟନ କରନ୍ତୁ",
select_location_from_map: "ନକ୍ଶାରୁ ଲୋକେସନ ଚୟନ କରନ୍ତୁ",
select_current_location: "ବର୍ତ୍ତମାନ ସ୍ଥାନ ଚୟନ କରନ୍ତୁ",
add_task: "କାର୍ଯ୍ୟ ଯୋଗ କରନ୍ତୁ",
requestVehicle: "ଗାଡି ଅନୁରୋଧ କରନ୍ତୁ",
request_vehicle: "ଗାଡି ଅନୁରୋଧ କରନ୍ତୁ",
your_requests: "ଆପଣଙ୍କ ଅନୁରୋଧ",
no_active_requests: "କୌଣସି କ୍ରିୟା ନାହିଁ",
no_requests_message: "ଆପଣଙ୍କୁ କୌଣସି ଅନୁରୋଧ ନାହିଁ। ଆପଣ ଆପଣଙ୍କ ସ୍ଥାନରେ ଗାଡି ନିର୍ଧାରଣ କରିପାରିବେ",
please_enter_request_vehicle_message: "ଦୟାକରି ସନ୍ଦେଶ ଦିଅନ୍ତୁ",
please_enter_typesOfRequestVehicle: "ଦୟାକରି ଗାଡି ଅନୁରୋଧ ଧରଣ ଚୟନ କରନ୍ତୁ",
request_your_vehicle: "ଆପଣଙ୍କ ଗାଡି ଅନୁରୋଧ କରନ୍ତୁ",
type_of_request_vehicle: "ଗାଡି ଅନୁରୋଧ ଧରଣ",
request: "ଅନୁରୋଧ",
request_vehicle_note: "ଟିପ୍‌: ଅନୁରୋଧିତ ଗାଡିଗୁଡ଼ିକ ଶୁଳ୍କରେ ପରେଇବ",
please_select_waste_type: "ଦୟାକରି ବର୍ଗନ୍ଧର ପ୍ରକାର ଚୟନ କରନ୍ତୁ",
delete: "ଡିଲିଟ୍",
domestic_waste: "ଘରୋଇଚା ଅପବାଦ",
water_tank: "ପାଣି ଟାଙ୍କ",
cesspool_tank: "ଛାଛଲର ଟାଙ୍କ",
party_waste: "ପାର୍ଟି ଅପବାଦ",
commercial_waste: "ବ୍ୟବସାୟିକ ଅପବାଦ",
construction_waste: "ନିର୍ମାଣ ଅପବାଦ",
description: "ବର୍ଣ୍ଣନା",
enter_your_suggestion: "ଆପଣଙ୍କ ସୁଝାବ ଲେଖନ୍ତୁ",
suggestion: "ସୁଝାବ",
mark_it_home_address: "ଏହା ଗୃହ ଠାରିବା ପାଇଁ ଚିହ୍ନିତ କରନ୍ତୁ",
segregated_waste_throw: "1. ଆପଣ ଆପଣଙ୍କ ଆପଣଙ୍କ ଅପବାଦ (ଭିଜ୍ଞତ ଓ ଶୁଖା) ଛଡି ଦେଇଥିବା?",
searching_nearest_publicToilet: "2. ଆପଣ କେମିତି ଗୁଡ଼ିକ ପାଇଁ Google ରେ ସର୍ବାଧିକ ସର୍ଚ କରିବେ?",
neighbourhood_area: "3. ଆପଣ ଆପଣଙ୍କ ସମ୍ପର୍କ କ୍ଷେତ୍ରରେ ଯାଉଥିବାକୁ ସବୁ ସମୟ ସଫାଇ ପାଇଁ ପାଇପାରିବେ?",
home_composting: "4. ଆପଣ ଘରେ କମ୍ପୋସ୍ଟିଂ କୁ ବାଣ୍ଟିବେ କି?",
your_age: "5. ଆପଣଙ୍କ ବୟସ କିତି?",
municipal_corporation: "ନଗର ସଂସ୍ଥା",
municipal_council: "ନଗର ପରିଷଦ",
history: "ଇତିହାସ",

contactUs: "ସମ୍ପର୍କ କରନ୍ତୁ",
notice_board: "ନୋଟିସ ବୋର୍ଡ",
track_garbageVan: "କଚରା ଗାଡି ଟ୍ରାକ୍ କରନ୍ତୁ",
garbageVan: "କଚରା ଗାଡି",
toilet_Locator: "ସାନ୍ଧାନୀର ଶାଉଚାଳୟ",
toilets: "ଶାଉଚାଳୟ",
community: "ସମୁଦାୟ",
payments: "ପେମେଣ୍ଟଗୁଡ଼ିକ",
update_account: "ଆପଣଙ୍କ ଆକାଉଣ୍ଟ ସେଟ୍ କରିପାରିବେ ପୂର୍ଣ୍ଣତାରେ",
create_account: "ଆପଣଙ୍କ ଆକାଉଣ୍ଟ ସୃଷ୍ଟି ହୋଇଛି",
share: "ଭାଗ କରନ୍ତୁ",
contact_us: "ସମ୍ପର୍କ କରନ୍ତୁ",
create_new_complaint: "ନୂତନ ଶିକାୟତ ସୃଷ୍ଟି କରନ୍ତୁ",
create_new_booking: "ନୂତନ ବୁକିଂ ସୃଷ୍ଟି କରନ୍ତୁ",
add_photo_or_video: "ଫୋଟୋ କିମ୍ବା ଭିଡିଓ ଯୋଗ କରନ୍ତୁ",
click_to_attach: "ଫୋଟୋ ଯୋଡ଼ନ୍ତୁ କିମ୍ବା ଆଟେଚ୍ କରନ୍ତୁ",
booking_type: "ବୁକିଂ ଧରଣ",
booking_date: "ବୁକିଂ ତାରିଖ",
quantity: "ପ୍ରମାଣ",
price: "ସ୍ଥିତି",
proceed: "ପ୍ରକ୍ରିୟା କରନ୍ତୁ",
please_select_bookingDate: "ଦୟାକରି ବୁକିଂ ତାରିଖ ଚୟନ କରନ୍ତୁ",
booking_confirmation: "ବୁକିଂ ନିଶ୍ଚୟିତି",
pay_now: "ଏବଂ ପେମେଣ୍ଟ କରନ୍ତୁ",
cash_on_delivery: "ଡାବା ରେ ପଇସା",
_tags: "ଟ୍ୟାଗ୍‌",
prefered_lan: "ପସନ୍ଦରେଖା ଭାଷାଗୁଡ଼ିକ",
_profile: "ପ୍ରୋଫାଇଲ",
no_history_found_for_this_date: "ଏହି ତାରିଖ ପାଇଁ କୌଣସି ଇତିହାସ ପାଇଁ ନାହିଁ",
bookings_not_available: "ଆପଣଙ୍କ ବୁକିଂସ ଉପଲବ୍ଧ ନାହିଁ। ଅନୁଗ୍ରହକରି ଆପଣଙ୍କ ପ୍ରଶାସନିକଙ୍କ ସହିତ ସମ୍ପର୍କ କରନ୍ତୁ..",
mobile_num_change: "ମୋବାଇଲ ନମ୍ବର ପରିବର୍ତ୍ତନ କରନ୍ତୁ",
update: "ଅଦ୍ୱିତୀୟ",
signup: "ସାଇନ୍‌ଅପ୍",
skip: "ଲୋମ୍ବା",
proceed: "ପ୍",
please_select_bookingDate: "ଦୟାକରି ବୁକିଂ ତାରିଖ ଚୟନ କରନ୍ତୁ",
booking_confirmation: "ବୁକିଂ ନିଶ୍ଚୟିତି",
pay_now: "ଏବଂ ପେମେଣ୍ଟ କରନ୍ତୁ",
cash_on_delivery: "ଡାବା ରେ ପଇସା",
_tags: "ଟ୍ୟାଗ୍‌",
prefered_lan: "ପସନ୍ଦରେଖା ଭାଷାଗୁଡ଼ିକ",
_profile: "ପ୍ରୋଫାଇଲ",
no_history_found_for_this_date: "ଏହି ତାରିଖ ପାଇଁ କୌଣସି ଇତିହାସ ପାଇଁ ନାହିଁ",
bookings_not_available: "ଆପଣଙ୍କ ବୁକିଂସ ଉପଲବ୍ଧ ନାହିଁ। ଅନୁଗ୍ରହକରି ଆପଣଙ୍କ ପ୍ରଶାସନିକଙ୍କ ସହିତ ସମ୍ପର୍କ କରନ୍ତୁ..",
mobile_num_change: "ମୋବାଇଲ ନମ୍ବର ପରିବର୍ତ୍ତନ କରନ୍ତୁ",
update: "ଅଦ୍ୱିତୀୟ",
signup: "ସାଇନ୍‌ଅପ୍",
skip: "ଲୋମ୍ବା",
proceed: "ପ୍ରକ୍ରିୟା କରନ୍ତୁ",
houseno: "ଘର ନମ୍ବର",
wardnum: "ପ୍ରଦେଶ ନମ୍ବର",
tagurself: "ଆପଣେ ଟାଗ କରନ୍ତୁ",
locateme: "ମୋର ସ୍ଥାନ ଚିହ୍ନିତ କରନ୍ତୁ",
settings: "ସେଟିଂସଗୁଡ଼ିକ",
location: "ସ୍ଥାନ",
add_location: "ସ୍ଥାନ ଯୋଗ କରନ୍ତୁ",
update_location: "ସ୍ଥାନ ଅଦ୍ୱିତୀୟ କରନ୍ତୁ",
alert: "ଆଲର୍ଟ",
show_alert: "ଆଲର୍ଟ ଦେଖନ୍ତୁ",
show_notification: "ବିଜ୍ଞପ୍ତି ଦେଖନ୍ତୁ",
assigned_tags: "ସଂମିଲିତ ଟ୍ୟାଗ୍‌",

add_tag: "ଟାଗ ଯୋଗ କରନ୍ତୁ",
add_newtag: "ନୂତନ ଟାଗ ଯୋଗ କରନ୍ତୁ",
ward_details: "ପ୍ରଦେଶ ବିବରଣୀ",
show_alerts: "ଆଲର୍ଟସଗୁଡ଼ିକ ଦେଖନ୍ତୁ",
make_my_profile_private: "ମୋ ପ୍ରୋଫାଇଲ ଗୋପନୀୟ କରନ୍ତୁ",
new_booking: "ନୂତନ ବୁକିଂ",
new_complaint: "ନୂତନ ଫିରେଇବା",
complaint_date: "ଫିରେଇବା ତାରିଖ",
complaint_no: "ଫିରେଇବା ନମ୍ବର",
muncipality: "ମଣ୍ଡଲୀୟ ସମିତି",
list_of_vehicles_available: "ଉପଲବ୍ଧ ଯାନବାହନ ସୂଚୀ",
enter_otp: "OTP ଦାଖଲ କରନ୍ତୁ",

no_notification: "କୌଣସି ବିଜ୍ଞପ୍ତି ନାହିଁ",
retake: "ପୁଣି ଛବି ତିଆରି କରନ୍ତୁ",
post_complaint: "ଫିରେଇବା ପୋଷ୍ଟ କରନ୍ତୁ",
select_complaint: "ଫିରେଇବା ପସନ୍ଦ କରନ୍ତୁ",
select_task: "କାର୍ଯ୍ୟ ପସନ୍ଦ କରନ୍ତୁ",
current_location: "ବର୍ତ୍ତମାନ ସ୍ଥାନ",
describe_issue: "ସୂଚନା ଦେଖାନ୍ତୁ",
capture_image: "ଛବି କ୍ୟାପ୍ଚୁର କରନ୍ତୁ",
select_type: "ପସନ୍ଦ ପରିବର୍ତ୍ତନ",
booking: "ବୁକିଂ",
active: "କ୍ରିୟାଶୀଳ",
assign: "ସମର୍ପଣା",
close: "ବନ୍ଦ କରନ୍ତୁ",
_close: "ବନ୍ଦ କରନ୍ତୁ",
refresh: "ପୁନର୍ନଯ୍ୟା",
age: "ବୟସ",
other_num: "ଅନ୍ୟ ନମ୍ବର",
feedback: "ପ୍ରତିକ୍ରିୟା",
ward_d: "ପ୍ରଦେଶ ବିବରଣୀ",
photos: "ଫୋଟୋ",
navigation: "ନେଭିଗେସନ୍",
view_n: "ନେଭିଗେସନ୍ ଦେଖନ୍ତୁ",
otp_sent_to: "OTP ଆପଣଙ୍କ ମୋବାଇଲ ନମ୍ବରରେ ପଠାଇଛି",
dear_user: "ପ୍ରୀତି ପୂର୍ବ୍ବକୁ ବ୍ୟବହାରକାରୀ",
congrats: "ଅଭିନନ୍ଦନ!",
Call_JMC: "JMC ହେଲପ୍‌ଲାଇନ୍‌କୁ କଲ୍‌ କରନ୍ତୁ",
full_name: "ପୁରା ନାମ",
mobile_num: "ମୋବାଇଲ ନମ୍ବର",
emailid: "ଇମେଲ୍ ଆଇଡି",
requestType: "ଅନୁରୋଧ ପ୍ରକାର",
bookedOn: "ବୁକ୍‌ କରାଯାଇଥିବା ତାରିଖ",
bookedFor: "ବୁକ୍‌ କରିବା ତାରିଖ",
assignedTo: "ଅବରୋଧିତ",
tId: "କାର୍ଯ୍ୟ ଆଇଡି",
req_veh: "ବାହନ ଅଭିରୋଧିତ",
taskType: "କାର୍ଯ୍ୟ ପ୍ରକାର",
ACTIVE: "କ୍ରିୟାଶୀଳ",
ASSIGNED: "ସମର୍ପିତ",
CLOSED: "ବନ୍ଦ କରାଯାଇଛି",
PENDING: "ଅପେକ୍ଷା ରହିଛି",
userprofile: "ବ୍ୟବସ୍ଥାପକ ପ୍ରୋଫାଇଲ",
editprofile: "ପ୍ରୋଫାଇଲ ସମ୍ପାଦନ",
area: "ଅଞ୍ଚଳ",
attended_by: "ଉପସ୍ଥିତି",
time: "ସମୟ",
acknowledgement: "ପ୍ରିୟାଦର୍ଶନ",
segregation: "ବିଭାଜନ",
no_data_found: "ଏହି ତାରିଖ ପାଇଁ କୌଣସି ତଥ୍ୟ ନାହିଁ",
go_to_c: "କ୍ୟାଲେଣ୍ଡର ଦେଖନ୍ତୁ",
confirm_to_exit: "ବାହାରିବା ନିଶ୍ଚିତି?",
hold_on: "ଧାରଣା ରଖନ୍ତୁ!",
tag_added: "ନୂଆ ଟାଗ ସଫଳତାରେ ଯୋଗ ହୋଇଛି!",
garbage_collected: "ରଦ୍‌ଡା ଜମିଆନହେଉଛି",
garbage_segregation: "ରଦ୍‌ଡା ବିଭାଜନ ନଥିବା",
garbage_picker_absent: "ରଦ୍‌ଡା ପିକର ଅନୁପସ୍ଥ",
unavailable: "ଅନୁପଲବ୍ଧ",
saving_complaint: "ଫିର୍ଦ୍‌ ଜମିଆନହେଉଛି",
command_center: "କମାଣ୍ଡ୍‌ ସେଣ୍ଟର",
please_enter_valid_otp: "ଦୟାକରି ବୈଧ OTP ପ୍ରବେଶ କରନ୍ତୁ",
keep_our_mun: "ଆମେର ବୁଗୁଡ଼ା ସଫାଇ ରଖନ୍ତୁ",
please_enter_suggerstion: "ଦୟାକରି ସୁଝାବ ପ୍ରବେଶ କରନ୍ତୁ",
please_enter_age: "ଦୟାକରି ଆୟୁ ପ୍ରବେଶ କରନ୍ତୁ",
your_feedback_submitted: "ଆપଣଙ୍କ ମୁଖ୍ୟମ୍ୟାନ ସଫଳତାରେ ପ୍ରସ୍ତୁତ ହୋଇଛି",
keep_our: "ଆମେର",
clean: "ସଫା",
app_version: "ଆପ୍‌ ଭର୍ଶନ:",
exit_app: "ଅପ୍ଲିକେସନ ବାହାରି ଯାଉଥିବା",
enter_your_text: "ଆପଣଙ୍କ ଟେକ୍ସଟ ପ୍ରବେଶ କରନ୍ତୁ",
choose_image: "ଛବି ଚୟନ କରନ୍ତୁ",
click_image: "ଛବି କ୍ଲିକ୍‌ କରନ୍ତୁ",
dear_user: "ପ୍ରିୟ ବ୍ୟବହାରକାରୀ",
location_updated: "ଆପଣଙ୍କ ଅବସ୍ଥାନ ସଫଳତାରେ ଅଦ୍ୟତନ କରାଯାଇଛି",
we_shall_contact_you_soon_T: "ଆପଣଙ୍କ କାର୍ଯ୍ୟ ସଫଳତାରେ ରଜିଷ୍ଟର କରାଯାଇଛି",
loading_com: "ଅଭିଯାନ ଲୋଡ ହେଉଛି",
loading_book: "ବୁକିଂ ଲୋଡ ହେଉଛି",
pick_image : "ପିକ୍ ଇମେଜ୍ |",
home_message : "ଆମର ଚାଟ୍ରାପୁରକୁ ସଫା ରଖନ୍ତୁ |",
upload_image : "ଦୟାକରି ପ୍ରତିଛବି ଅପଲୋଡ୍ କରନ୍ତୁ |",
please_enter_number: "ଫୋନ ନମ୍ବର ଦୟାକରି ଦିଅନ୍ତୁ",
please_enter_valid_info: "OTP ଦୟାକରି ଦିଅନ୍ତୁ",
please_select_image: "ଛବି ଚୟନ କରନ୍ତୁ",
permission_to_acess_storage: "ସ୍ଟୋରେଜ୍ ପ୍ରବେଶ ଅନୁମତି ଆବଶ୍ୟକ। ଦୟାକରି 'ସିରଫ ମିଡିଆ ପାଇଁ ପ୍ରବେଶ ଦିଅନ୍ତୁ' ରେ ଚୟନ କରନ୍ତୁ।",
while_storing_image: "ଉଫ୍ !! ଛବି ରଖିବାକୁ ଭୁଲିଆଗଲା",
map: "ମ୍ୟାପ୍",
satelite: "ସେଟେଲାଇଟ୍",
failed_to_insert_user: "ବ୍ୟବହାରକାରୀ ଯୋଗା ହେଉନାହିଁ",
please_select_c_type: "ଅଭିଯୋଗ ପ୍ରକାର ଚୟନ କରନ୍ତୁ",
please_enter_comment: "ଦୟାକରି ମତାମତ ଦିଅନ୍ତୁ",
comment: "ମତାମତ",
please_select_b_type: "ବୁକିଂ ପ୍ରକାର ଚୟନ କରନ୍ତୁ",
please_select_waste_type: "ଦୟାକରି ବୁକିଂ ପ୍ରକାର ଚୟନ କରନ୍ତୁ",
req_veh: "ବୁକିଂ ପ୍ରକାର",
select_task: "ବୁକିଂ ଚୟନ କରନ୍ତୁ",
confirm_to_exit: "ବାହାରିବା ପୁଷ୍ଟି?",
history_t: "ଇତିହାସ",
please_select_all: "ସମସ୍ତ ପ୍ରଶ୍ନ ଉତ୍ତର ଦିଅନ୍ତୁ",
please_select_location_by_clicking: "ମାନଚିତ୍ରରେ ବଟନ୍ କ୍ଲିକ କରିପାରି ସ୍ଥାନ ଚୟନ କରନ୍ତୁ",
please_enter_d_no: "ଦରବାର ନମ୍ବର ଦୟାକରି ଦିଅନ୍ତୁ",
user_with_same_d_no_exists: "ସମାନ ଦରବାର ନମ୍ବରରେ ବ୍ୟବହାରକର୍ତ୍ତା ଅଛନ୍ତି",
d_no: "ଦରବାର ନମ୍ବର",
cannot_update: "ଆପଣଙ୍କୁ ଏହି ଘରେଲୁଆ ଅପଡେଟ କରିବାକୁ ଅନୁମତି ନାହିଁ। ଦୟାକରି ଅଡମିନ୍‌ରେ ସମ୍ପର୍କ କରନ୍ତୁ",
getting_this_month_report: "କୃପା କରି ଅପେକ୍ଷା କରନ୍ତୁ, ବର୍ତ୍ତମାନ ମାସର ରିପୋର୍ଟ ପ୍ରାପ୍ତ କରାଯାଉଛି",
please_enter_d_no_properly : "କବାଟ ସଂଖ୍ୟା ନିଶ୍ଚିତ ଭାବରେ ବର୍ଣ୍ଣମାଳା ଅକ୍ଷର ହେବା ଉଚିତ (EX: ABCD123FE)",
please_switch_location : "ଦୟାକରି ମୋବାଇଲରେ ଆପଣଙ୍କର ଅବସ୍ଥାନ ଟର୍ନ୍ ଅନ୍ କରନ୍ତୁ |",
switch_on_location : "ତୁମର ଅବସ୍ଥାନ ଟର୍ନ୍ ଅନ୍ କର |",
location_permission : 'ଦୟାକରି ଆପଣଙ୍କ ଫୋନରେ ଅବସ୍ଥାନ ଯାଞ୍ଚ କରନ୍ତୁ ଏବଂ ଏହି ମୋଡ୍ ବନ୍ଦ କରିବାକୁ "ସବୁବେଳେ ଅନୁମତି ଦିଅନ୍ତୁ" ଚୟନ କରନ୍ତୁ |',


   
}